### ISSUE TITLE
RegistryEntryBuilder creates two unrelated InformationBuilder.Resource objects

### ISSUE THREAD

**Issue by chklauser** [crnk-project/crnk-framework#117]
The `DefaultRegistryEntryBuilder` constructs two different `InformationBuilder.Resource` objects. One through its `resource()` method, the other inside `DefaultInformationBuilder.createResourceRepository(java.lang.Class<?>, java.lang.String)`. The former can be customized whereas the latter gets inserted straight into the `io.crnk.core.engine.internal.information.DefaultInformationBuilder.DefaultResourceRepository`. That one will have `null` as its `resourceType` and `resourceClass`.

One solution to this would be to change the `resource()` method implementation to return the resource that gets created as part of the `ResourceRepository`.

```java
@Override
public InformationBuilder.Resource resource() {
    if (resource == null) {
        resource = resourceRepository().information().resource();
    }
    return resource;
}
```

Affected version of crnk: GitHub master

**Comment by remmeier** [comment]
there are settings on InformationBuilder.Resource to set resourceType and resourceClass. Or do I miss something?

**Comment by chklauser** [comment]
Let *R1* be the `InformationBuilder.Resource` object you get by calling `io.crnk.core.engine.internal.registry.DefaultRegistryEntryBuilder#resource`. Let *R2* be the `InformationBuilder.Resource` object that gets created as part of calling `io.crnk.core.engine.internal.registry.DefaultRegistryEntryBuilder#resourceRepository`. The two objects are never the same.

Have a look at the `io.crnk.core.engine.internal.registry.DefaultRegistryEntryBuilder#build` method. On the first line, the method uses *R2*:
```java
ResourceRepositoryInformation repositoryInformation = resourceRepository.information().build();
```
Towards the end, it uses *R1*
```java
ResourceInformation resourceInformation = resource.build();
```
It then combines the two into the actual entry:
``java
RegistryEntry entry = new RegistryEntry(resourceInformation, repositoryInformation, resourceEntry, relationshipEntries);
```

An now we have a bastard entry where one half contains the information that we configured (`resourceInformation`) and the other half uses an uninitialized object as part of `repositoryInformation`). 

And no, it's not possible to customize the `InformationBuilder.Resource` object inside `RegistryEntryBuilder.ResourceRepository` because the `InformationBuilder.Resource` is not exposed in its interface. But even then, I don't think it makes sense to have two Java objects that are supposed to describe the same thing. Changes to one of them are not repeated in the other, source of weird bugs etc.
