### ISSUE TITLE
ResourceMetaProviderImpl doesn't work with dynamically created resources

### ISSUE THREAD

**Issue by chklauser** [crnk-project/crnk-framework#118]
I try to dynamically create resources and resource repositories. The `ResourceInformation` objects I create all have different `resourceType`s (the domain-specific name of the resource), but they all share `io.crnk.core.engine.document.Resource` as the runtime implementation for constructing responses.

The problem I run into is that the `ResourceMetaProviderImpl.discoverElements` method seems to ignore the information available in `ResourceInformation` and only constructs its `MetaResource` object based on the `resourceClass` (which is the same for all of my dynamic resources). It then goes on to construct the `MetaResourceRepository` in its `discoverRepository` method, where all of my repositories get the same `id`. At the moment the `id` is entirely based on the `MetaResource` and therefore ignores the `resourceType` I assigned to my individual resources.

This results in an assertion failure when the second repository gets added to the `MetaLookup` structure as all of my `MetaResourceRepository`s get assigned the same id.
```java
// io.crnk.meta.MetaLookup.add
PreconditionUtil.assertNull(element.getId(), currentElement);
```

**Comment by remmeier** [comment]
Yes, that class should change a bit for this use case. Most likely useResourceRegistry must become true. Have to check whether there is any use case left. Then discoverElements() will setup MetaResource instances along with the existing MetaResourceRepository instances.

**Comment by remmeier** [comment]
- meta elements for different use cases (JPA entities, resources) now clearly separated by MetaPartition.
- there is a base partition for shared types (string, integer).
- each partition can set its own rule how to assign, for example identifiers.
- assignement of ids has mostly been automated for the resource partition. resource objects get a "resources.<resourceType>" id like "resources.person". Related objects like informations and dtos automatically share the meta id prefix with resources if they are located next to them or in a subpackage.
- the use of resourceType to compute the id allows to fix the given issue here. The implementation class is now irrelevant to compute ids.
