### ISSUE TITLE
[crnk-jpa] JsonApiResource is being ignored

### ISSUE THREAD

**Issue by mohlek** [crnk-project/crnk-framework#133]
crnk version: 2.2.20171015181129

```Java
@Entity
@Table(name = "my_table")
@Getter
@Setter
@JsonApiResource(type = "awesome-class")
public class AwesomeClass {
...
}
```

Given that class, the repository should be `api/awsome-class` insead of `api/awesomeClass`

**Comment by remmeier** [comment]
support needs to be added in JpaResourceInformation.getResourceType. Maybe some more flexbility in the area would be great next to support for JsonApiResource. Like being able to provide a method that does the entity to resource name mapping. Or to add a prefix like "entity/awesome-class" to all entity resources.

**Comment by remmeier** [comment]
resolved in the meantime
