### ISSUE TITLE
Possibility to remove trailing slash from requests

### ISSUE THREAD

**Issue by cljk** [crnk-project/crnk-framework#136]
I started a project which syncs some data to an OroCRM instance (https://www.orocrm.com/ - https://github.com/oroinc/crm-application). OroCRM relys on PHP Symphony and they heavily use JSON-API - using a client API for that would be a good idea. 

So I started trying out "crnk-client" and got to a REALLY stupid problem connecting to OroCRM with crnk-client... My test code is
```
CrnkClient client = new CrnkClient("http://localhost:9090/app_dev.php/api");
ResourceRepositoryV2<OroCrmAccount, Long> accRepo = client.getRepositoryForType(OroCrmAccount.class);
List<OroCrmAccount> accs = accRepo.findAll(new QuerySpec(OroCrmAccount.class));
```
In line 3 I get an Exception: "io.crnk.core.exception.ResourceNotFoundException"
Using Burp suite I found out that the HTTP-request on first sight seems to be correct. The client requests
```
/app_dev.php/api/accounts/
```
and receives a 404 not found. I checked back the OroCRM REST Sandbox.... and the official client requests
```
/app_dev.php/api/accounts
```
The trailing slash makes the difference for OroCRM and returns "404 no route found" if the slash is added. Is there a simple possibility for me to remove the trailing slash in requests to the repository?

**Comment by remmeier** [comment]
check the spec, yes, the slash should rather not be there and that should be fixed in general. Somewhere in the area of DefaultQuerySpecSerializer or a related class we could remove that. Potentially the backend side then needs a fix as well.

**Comment by remmeier** [comment]
avilable in 2.3 soon
