### ISSUE TITLE
Spring Boot 2.0: Links in responses have the resource type twice (and are therefore invalid)

### ISSUE THREAD

**Issue by davidyscott** [crnk-project/crnk-framework#137]
Steps to reproduce:
I have a new application using spring-boot-starter-web 2.0.0M5.
I have a resource configured using `@JsonApiResource(type = "entity")` (real name obfuscated).
I make the following POST request to `/api/entity`:
```
{
  "data": {
    "type": "entity",
    "attributes": {
      "name": "entity1"
    }
  }
}
```
The response is
```
{
  "data": {
    "id": "1",
    "type": "entity",
    "attributes": {
      "name": "entity1"
    },
    "links": {
      "self": "http://localhost:9000/api/entity/entity/1"
    }
  }
}
```
The problem is the link should instead point to `http://localhost:9000/api/entity/1`.
I believe the issue is that the `request`'s `servletPath` has changed with new version of SpringBoot / Tomcat to already include the resource type, so that [this line](https://github.com/crnk-project/crnk-framework/blob/8d8b11789cc3b450f811f1c59d55391a2706b58e/crnk-servlet/src/main/java/io/crnk/servlet/internal/ServletRequestContext.java#L118) no longer does anything, and therefore [this line](https://github.com/crnk-project/crnk-framework/blob/8d8b11789cc3b450f811f1c59d55391a2706b58e/crnk-core/src/main/java/io/crnk/core/engine/internal/registry/ResourceRegistryImpl.java#L111) appends the resource type again.

**Comment by remmeier** [comment]
your hints seem good. I guess the example app should be updated to Spring Boot 2.x and the implementation adjusted to deal with both 1.x and 2.x.

**Comment by davidyscott** [comment]
Unfortunately, I think my earlier conclusions about the cause were too simple.  Consider the GET request `/entity?include=otherEntity`.
Stripping down the response to focus only on the links:
```
{
  "data": [
    {
      "relationships": {
        "otherEntity": {
          "links": {
            "self": "http://localhost:9000/api/entity/entity/1/relationships/otherEntity",
            "related": "http://localhost:9000/api/entity/entity/1/otherEntity"
          }
        }
      },
      "links": {
        "self": "http://localhost:9000/api/entity/entity/1"
      }
    }
  ],
  "included": [
    {
      "id": "1",
      "type": "otherEntity",
      "links": {
        "self": "http://localhost:9000/api/entity/otherEntity/1"
      }
    }
  ]
}
```
So every single link has an extra instance of `entity`, but it's not always duplicated (which is what I'd thought initially).

**Comment by remmeier** [comment]
yes, if it wrong at one place, it willbe wrong everything. Things like paging links will also be wrong.

since it is a spring boot milestone, I would also consider creating a spring boot ticket. Manybe the entire thing is undesired.

**Comment by remmeier** [comment]
BTW: as a short-term measure for today, CrnkBoot.setServiceUrlProvider allows to set a custom implementation that gives "http://localhost:9000/api"

**Comment by remmeier** [comment]
e.g. ConstantServiceUrlProvider

**Comment by remmeier** [comment]
now run into this as well due to a wrong ServletPath. If for example

`crnk:
  pathPrefix: /api
`

is configured, it will truncate the servlet path accordingly and compute proper urls.
