### ISSUE TITLE
Provide an implementation of getResourceUrl instead of deprecated one

### ISSUE THREAD

**Issue by vicmosin** [crnk-project/crnk-framework#148]
Currently in order to test web-layer of an web-app, I have to retrive the urls dynamically via 
`String url = resourceRegistry.getResourceUrl(resourceRegistry.findEntry(User.class).getResourceInformation());`
which is kinda ugly and it's deprecated.. Any feedback why it was done and what's the new way?
Thank you in advance

**Comment by remmeier** [comment]
let us just remove that deprecation? The area has been cleaned up a while ago, resp. the API reduced to the bare minmum. There is currently not really a better place that comes into my mind.

**Comment by remmeier** [comment]
release available later today
