### ISSUE TITLE
[crnk-jpa] filter by null value

### ISSUE THREAD

**Issue by mohlek** [crnk-project/crnk-framework#150]
What is the best practice to filter a field by `NULL` ?
In my tables there are plenty of fields with a `NULL` value. I'd like to request a resource with filter[lastEdited] = NULL` . Is there any way to do so?

**Comment by mohlek** [comment]
@buschtoens

**Comment by remmeier** [comment]
I guess that is more a general QuerySpec question that is currently unresolved. resp. the json api spec does not have recommendation on that matter. DefaultQuerySpecDeserializer.deserializeFilter would be the place. I suspect crnk-jpa will then properly pick the null up.

one possiblitiy would be to explicitly map the value "null" to null. There should be a possiblity to distinguish between null and empty string.

**Comment by OskarD** [comment]
@remmeier any progress on this? Is there some way I can help?

**Comment by remmeier** [comment]
nothing from my side so far. PRs are always welcomed. This one would be a fairly small one. Altough maybe we should set up something more generic? so allows allow other expressions next to "null", like "now " or "now + 1h" for dates and stuff. Is there a good existing expression language we could make use of maybe?

**Comment by mohlek** [comment]
> so allows allow other expressions next to "null", like "now " or "now + 1h" for dates and stuff. Is there a good existing expression language we could make use of maybe?

I like the idea but not as part of the core. I think crnk should stick to the spec as close as possible.

**Comment by OskarD** [comment]
As much as I wish that the spec covered this, I have to agree with @mohlek 

But I don't know how to do this myself, unfortunately, so I am hoping that someone else will ❤️

**Comment by remmeier** [comment]
yes, we can also just get started with that null.

**Comment by mohlek** [comment]
:heart_eyes:
