### ISSUE TITLE
Unable to deploy war file to WAS 8.5.5.12 on IBM Java 1.8

### ISSUE THREAD

**Issue by afrizalchen** [crnk-project/crnk-framework#155]
The application can't be started. With the following error:

`javax.enterprise.inject.UnproxyableResolutionException: WebBeans with api type with normal scope must be proxiable to inject.
io.crnk.core.repository.RelationshipRepositoryBase has no explicit no-arg constructor!A public or protected constructor without args is required!`

**Comment by remmeier** [comment]
RelationshipRepositoryBase can be subclassed an a protected constructor added to led Weld create dynamic proxies, then the issue goes away. But we should add that private constructor to RelationshipRepositoryBase  as well.

**Comment by afrizalchen** [comment]
`public class BaseRelationshipRepository<T, I extends Serializable, D, J extends Serializable> extends RelationshipRepositoryBase {
    protected BaseRelationshipRepository() {
        super(null, null);
    }
    protected BaseRelationshipRepository(Class<T> sourceResourceClass, Class<D> targetResourceClass) {
        super(sourceResourceClass, targetResourceClass);
    }
}`
I implemented the class above, and change my relationship repo classes to this one. But the same error still persists.

**Comment by remmeier** [comment]
is there a default constructor? BaseRelationshipRepository()?

**Comment by afrizalchen** [comment]
Default constructor
`protected BaseRelationshipRepository()  { super(null, null); 
}`

**Comment by afrizalchen** [comment]
I solve this by copying the RelationshipRepositoryBase.java from CRNK into my project. And added the no-args constructor. NOTE that this changes should be temporarily until CRNK code base is updated.

**Comment by remmeier** [comment]
constructor added accordingly
