### ISSUE TITLE
Move to Java 8 as minimum requirement

### ISSUE THREAD

**Issue by vicmosin** [crnk-project/crnk-framework#157]
Any objections to deprecate custom impl of Optional in favor of java 8's Optional?

**Comment by remmeier** [comment]
currently yes, it is more of a mid-term thing. Currently we still provide Java 7 support. Now with the release of Java 9 plan would be slowly move to Java 8 as minimum requirement. So I can do an annotation. As of this summer, Java 7 support was still requested (under the condition to get rid of it this year).

At that point all current uses of the crnk Optional have to be deprecated and offer a new java Optional alternative. If that is done, the crnk Optional itself can be deprecated and removed. I would  like to avoid deprecating things before providing an altnerative. But I thnk usage of the crnk Optional in non-internal API is rather limited.

**Comment by vicmosin** [comment]
Yeah, but you can't do both things since internal Optional is used within public API methods.. So I would deprecate Optional as a first phase and replace it with java's Optional later. But question is what to do with public methods, should they be deprecated as well?

**Comment by remmeier** [comment]
it is in io.crnk.core.utils, so it is not considered internal. But it use seems quite limited. I put a message in the forum and will update the web page soon to state that Java 7 is going away. Then we proceed here. I don't expect any hold up.

**Comment by remmeier** [comment]
java 8 it is from crnk 2.4+
