### ISSUE TITLE
QuerySpec's custom parameters

### ISSUE THREAD

**Issue by vicmosin** [crnk-project/crnk-framework#161]
I couldn't find any way to support custom parameters.. All interfaces depend on `QuerySpec` which is class i.e. one can't just use inheritance or implement his own implementation (if it was an interface for example).
From other side, there is a `QuerySpecDeserializer` interface which might be overriden.. So question is what's the point of implementing your own deserializer if all of the repos are hardcoded to work with `QuerySpec`??

What if we introduce a list of unsupported (and provided) query params as  map or something.. This way one can override deserializer and have his custom fields accessable..

**Comment by remmeier** [comment]
it is not something that people like seeing as the JSON API specification is fairly strict regarding the set of available parameters. What would you need for? 

one can let the QuerySpecDeserializer ignore unknown parameter and access it with http://www.crnk.io/documentation/#_access_to_http_layer. But that is not recommended to do so. The later is rather/typically used to transmit further HTTP headers (security, tracing, internationalization, etc.)

**Comment by vicmosin** [comment]
Well, sometimes API needs to provide more param types than described in specs.. That's exactly the case I have - one of the resources should be filtered not by limit/offset but via other params.

**Comment by remmeier** [comment]
do you have a concrete example? technically the offset/limit is only a paging recommendation, so it would be thinkable to add more generic support in the area.

**Comment by vicmosin** [comment]
Imagine stream API where you don't have any real pages but chunks of data.. and in order to get the "offseted" data you use `since` param which defines from which id/timestamp/whatever start to fetch data

**Comment by makepanic** [comment]
The only thing that jsonapi defines about additional query params is their naming constraints: 

http://jsonapi.org/format/#query-parameters

This means it's probably a good idea to expose handling of them to a crnk user.

**Comment by vicmosin** [comment]
Yeah.. As I wrote already, the simpliest solution would be to expose all the additional query params as `Map<String, Object>` which will be filled in case of `setAllowUnknownAttributes(true)`..

**Comment by remmeier** [comment]
yes, more general paging implementation would be something worth to support, with offset/limit being one flavor of it.

the stream api use case above I guess can be implemented with a filter and offset parameter. But maybe there is a way to include this directly with paging and let crnk to some more things out-of-the-box (like prev/next page computation). Have to think about that. Recommendations welcomed as well.

adding http request parameters to QuerySpec is not necessary. HttpRequestContextAware is already in place to get access to the underlying HTTP request. See http://www.crnk.io/documentation/#_access_to_http_layer. Mostly used for HTTP header access. But it can also be used to access any other parameter, altough that is still not recommended as it is not jsonapi.

**Comment by vicmosin** [comment]
> the stream api use case above I guess can be implemented with a filter and offset parameter.
it is not since you never know how many additional parameters you need to provide to endpoint.. Some of them might be semantically similar to filter definitions, some of them - not..

**Comment by vicmosin** [comment]
@remmeier 
could you please point me how to get this `HttpRequestContextProvider` instance? I tried via `ModuleRegistry` and `CrnkBoot::moduleRegistry` but once I try to inject them into repository, I get 
```
io.crnk.core.exception.RepositoryNotFoundException: Repository for a resource not found
```

**Comment by remmeier** [comment]
do you have a complete stack trace? have you used HttpRequestContextAware?

**Comment by vicmosin** [comment]
@remmeier 
so after all I implemented the functionality via introducing custom module which reads the query params from `HttpRequestContextProvider ` directly. Thanks for pointing me to this. So my PR is mostly useless.. If you want, I could add the module as a separate project module, so let me know.

**Comment by remmeier** [comment]
yes I guess would not be need. Or what what do you mean with a separate project module? 

in general the custom/unknown attribute thing should not be pushed to heavily. We should rather have another look at paging.

**Comment by rehab-reda0** [comment]
@vicmosin  Can u share this module please

**Comment by vicmosin** [comment]
@rehab-reda0 https://gist.github.com/vicmosin/48f31a911c5282e2a20c76808655c0f8

In order to use it it should be enough to define bean of that type

**Comment by rehab-reda0** [comment]
Thank you @vicmosin  so much! so where u are calling the getQueryParams function ? inside the repo or where ?
