### ISSUE TITLE
Crnk forces me to have inverse relations

### ISSUE THREAD

**Issue by systemfreund** [crnk-project/crnk-framework#174]
JSON-API does not mandate that for every relation there must be an inverse relation, yet crnk insists on having them.

What do you think about making inverse relations optional/configurable?

**Comment by remmeier** [comment]
where have you seen that behavior? should not be the case.

**Comment by systemfreund** [comment]
I'm sorry i think i went too fast... I can't reproduce it any more, but I could swear that i was given an exception mentioning that a inverse relationship could not be found.

I'm closing this ticket again
