### ISSUE TITLE
Add custom relationships/links to resource

### ISSUE THREAD

**Issue by vicmosin** [crnk-project/crnk-framework#178]
Here is the case - I have a crnk resource A and custom resource B, which is responsible for file upload (imagine avatar of particular user). It's obvious that I can't implement B as a crnk resource. What I need is some mechanism to manually add the link/relation to resource. I tried all the filters so far, and the only one that might help is resource filter, but it requires a valid relation-field object which is not my case. Is there any other filter to implement what I need? Or the only possible way is to implement custom jackson module?

**Comment by aawaken** [comment]
Hello! Why is the ticket closed? Any solution found?
Thanks

**Comment by remmeier** [comment]
I guess the solution was found after opening the ticket. An example is given here:

http://www.crnk.io/releases/stable/documentation/#_jsonapilinksinformation

A repository then simply has to fill-up that links information like any other kind of data. No special filters or anything necessary.
