### ISSUE TITLE
Id field not found in class

### ISSUE THREAD

**Issue by tatemz** [crnk-project/crnk-framework#187]
I am getting this error with the model below. Is there a common debugging step that could help fix this exception?

```
io.crnk.core.exception.ResourceIdNotFoundException: Id field not found in class
```

```java
@JsonApiResource(type = "task")
public class Task {

	@JsonApiId
	private Long Id;
	
	public Long getId() {
		return Id;
	}
	
	public void setId(Long Id) {
		this.Id = Id;
	}
}
```

**Comment by tatemz** [comment]
I was using the 2.4.X builds, but switching to 1.0.20170721162741 fixed this issue.

Either the docs are out of date or the 2.4.X build is not working. 🤷‍♂️

**Comment by remmeier** [comment]
I suspect the upper case "Id" attribute is the issue. It should rather be lower case "id".

**Comment by tatemz** [comment]
I tried lowercase as well... same result.

**Comment by remmeier** [comment]
please reopen if the issue still persists with a small/reproducable test or a complete stack trace.
