### ISSUE TITLE
Filtering by multiple resources is not implemented

### ISSUE THREAD

**Issue by inssein** [crnk-project/crnk-framework#188]
"/comments?filter[id]=1,2" should return comments 1 and 2, but currently returns "Request parameters error"

**Comment by remmeier** [comment]
filter[id]=1&filter[id]=2 will work. But potentially/probably support for comma separator should be added as well to DefaultQuerySpecDeserializer.deserializeFilter(...).

**Comment by OskarD** [comment]
This would be a well appreciated implementation! Any progress?

**Comment by inssein** [comment]
I just switched to using @remmeier's idea. I did have an implementation that solved it, but it is not very flexible for strings that can potentially have comma's, etc.

**Comment by remmeier** [comment]
supported by now with comma as seperator for collection of values
