### ISSUE TITLE
findOne is not returning 404 when entity does not exist

### ISSUE THREAD

**Issue by remmeier** [crnk-project/crnk-framework#19]
from @phuo1032:

This issue seemed to be fixed at some point from a PR

#272

But the latest version does not have this change any more.
https://github.com/katharsis-project/katharsis-framework/blob/master/katharsis-core/src/main/java/io/katharsis/core/internal/dispatcher/controller/ResourceGet.java

The test case that verifies the NOT_FOUND status is also not there.
https://github.com/katharsis-project/katharsis-framework/blob/master/katharsis-core/src/test/java/io/katharsis/core/internal/dispatcher/controller/resource/ResourceGetTest.java

Is this a design change for restoring the previous behavior or am I suppose to throw the NOT_FOUND exception manually?

**Comment by mohlek** [comment]
ref #41
