### ISSUE TITLE
Adding custom query params to paging

### ISSUE THREAD

**Issue by vicmosin** [crnk-project/crnk-framework#203]
Hi,
here is the case: we use custom module which allows us to work with custom query params and retrieve data based on them. Now, once we add default paging mechanism, we want that custom params will also be taken into consideration while building the url.

Example:
Request:   `GET /some?page[limit]=10&limit=10&custom1=X&custom2=Y`
Actual:      `next: "/some?page[limit]=10&page[offset]=10"`
Expected: `next: "/some?page[limit]=10&page[offset]=10&custom1=X&custom2=Y"`

Is this possible to do it with built-in / module methods?

**Comment by remmeier** [comment]
no as it goes against the JSON API specification. Application should strive to stick to this. There is the possiblity to transmit other kind of data through HTTP headers and meta information. Usually this suffices. But it is possible to at least get access non-specified parameters. 

If there is a good use case, the self/link computation would have to be generalized.

**Comment by vicmosin** [comment]
Well, first of all we already have similar discussion. My point was that it would be nice have more generic mechanism of supporting all kind of parameters, not only hardcoded via crnk. My main argument for this - specification actually doesn't require filtering mechanism to be the way it's implemented. It's a **recommendation** only. That's why actually I believe `QuerySpecDeserializer` and link generation should still be able provide any input params, not "swallowing" them only because it's not mentioned in recommendation.. I.e. crnk should follow that recommendation by supporting those params (filter etc), but any other params shouldn't be treated as invalid.

**Comment by remmeier** [comment]
jsonapi recommends offset/limit, but specifies the page parameter. custom1, custom2 would not seem to fit in there. 

tickets should probably alinged a bit, there is the possibility of a more custom paging and the support for arbitrary parameters that  cc

**Comment by vicmosin** [comment]
As I said, it's not about 
> custom1, custom2 would not seem to fit in there.
My point is that crnk's default behavior is just ignore/throw error in case of any custom param which isn't covered by recommendation. It's the way it is now.
The other way might be to allow it and just append it to every server-side generated link (i.e. proxy). Crnk doesn't have to restrict custom1 or custom2, it's not his business after all, what business logics will do with them.

**Comment by remmeier** [comment]
jsonapi specifies the page parameter and recommends offset, limit. custom1, custom2 would not fit here as far as i understand, but page[custom] would.

tickets should potentially be aligned a bit, one for more generic paging and none to sideline jsonapi where really needed. both doable, but the later more of an emergency measure and not recommended..

**Comment by remmeier** [comment]
one to sideline without that n...

**Comment by remmeier** [comment]
the error can be disabled, but as said it violates the spec.

**Comment by vicmosin** [comment]
yes, error can be.. but crnk still  swallowes all of the custom (i.e. not covered by recommendation) query params while generating the link..

**Comment by remmeier** [comment]
updated this ticket: https://github.com/crnk-project/crnk-framework/issues/47 which deals with more generic paging. But that one only include the specified page[...] parameter. 

Potentially a dedicated ticket do move any kind of Link computation into some class would also be  worthwhile to have.
