### ISSUE TITLE
ReflectionsServiceDiscovery with custom serviceLocator

### ISSUE THREAD

**Issue by kkamkou** [crnk-project/crnk-framework#205]
Problem: `JsonServiceLocator` is marked as `@deprecated`. There is no way to re-use the reflection discovery with a custom locator. In particular I'm trying to properly interpret the comment: `@deprecated make use of ServiceDiscovery and ServiceDiscoveryFactory`. Please clarify the logic in this case. What is the right way to re-use the `ReflectionsServiceDiscovery`?

Example working solution (discovery via reflections injecting a `datastore` without DI) which is incorrect because of `@deprecated` annotation:
  ```java
    final CrnkFeature crnk = new CrnkFeature();
    crnk.getBoot().setServiceLocator(new JsonServiceLocator() { // <<< @deprecated
      @Override
      public <T> T getInstance(Class<T> clazz) {
        try {
          return clazz.getDeclaredConstructor(Datastore.class).newInstance(datastore);
        } catch (ReflectiveOperationException e) {
          throw new IllegalStateException(e);
        }
      }
    });
  ```

**Comment by novaterata** [comment]
Yes please, as it stands I don't understand how I would manually inject into a ResourceRepository for instance. We use dagger2 for DI, and I'm at a loss reading the documentation.

**Comment by novaterata** [comment]
And the documentation says, oh if you are going to do this than read about modules, which is an overloaded term and seems to involve reading the rest of the entire documentation.

**Comment by remmeier** [comment]
there is a section about service discovery here:

http://www.crnk.io/documentation/#_implement_a_custom_discovery_mechanism

if you make use of a so far non-supported dependency injection framework (like dagger), it might be best to implement that ServiceDiscovery interface. Only two methods to implement. CDI, Spring, Guava provide examples.

JsonServiceLocator, etc. has been replaced in favor of ServiceDiscovery.

**Comment by novaterata** [comment]
Please consider adding an example of the simplest way to inject something into a repository using manual injection. I will try to figure it out myself, but as it stands it's not as obvious as you must think

**Comment by remmeier** [comment]
can do later today, new SimpleModule, there addRepository, then add that module to the crnk setup like CrnFeature or CrnkBoot or . ..

**Comment by remmeier** [comment]
=> no discovery

**Comment by kkamkou** [comment]
I consider the reply as: `getBoot().setServiceLocator()` is also deprecated.
