### ISSUE TITLE
Schedule removal of deprecated API

### ISSUE THREAD

**Issue by remmeier** [crnk-project/crnk-framework#207]
A number of deprecated API are around for almost 1 1/2 years, most notably QueryParams and deprecated annotations. Sometime this year those should be removed if there are no objections. This in turn would allow to cleanup and simplify quite a number of things.

The result would be crnk 3.0 without breaking changes for everybody having got rid of those deprecated usages.

**Comment by remmeier** [comment]
note also that there is no rush for this change, so let us say June 2018 as target. Both can also be easily delayed or fast tracked.

**Comment by remmeier** [comment]
only QueryParams or also the annotated repositories? later are actually much worse in terms of complexity it currently causes in the code base. There is not much of an issue in keeping QueryParams for a while.

**Comment by weaselmetal** [comment]
We have quite a a couple of endpoints that use the annotation based approach.
I would imagine that those are easier to migrate over to the interface approach than migrating QueryParams. But I haven't tried.

**Comment by remmeier** [comment]
for the first round of removals, the following API will be removed:

- io.crnk.legacy.repository.annotations (non-Interface-based repositories) => use interfaces, easy to migrate
- io.crnk.legacy.queryParams.QueryParamsParser (QueryParamsConverter can be used instead with QuerySpec as main query API) => unlikely to be in use anywhere anymore
- RequestContextParameterProvider (related to io.crnk.legacy.repository.annotations)
- JsonServiceLocator & ReflectionsServiceDiscovery => deprecated in favor of various other ServiceDiscovery a long time ago => easy to migrate to

expected removal date is July/August. Migration effort is minimal should anybody still make use of those. This in turn will allow to simplify the code base.

not in scope for removal is QueryParams, that is continued to be deprecated but supported.

**Comment by remmeier** [comment]
- the repository annotations have been removed as scheduled
- QueryParams implementation has been simplified and can continued to be used through the QueryParamsConverter, which is the recommended setup for a long time. Direct support without conversion is no longer supported.
