### ISSUE TITLE
Ability to respond with 202 (Accepted) to a create resource request

### ISSUE THREAD

**Issue by vhothur** [crnk-project/crnk-framework#208]
Would like to have the ability to return 202 (Accepted ) status code when creating a resource that is queued up for processing. 
And the ability to include Location in the header when returning 202 status code

**Comment by remmeier** [comment]
Out-of-the-box not yet possible, but with some minor improvements. The code in question is in ResourcePost:

`return new Response(responseDocument, HttpStatus.CREATED_201);`

How about a Processior HttpStatusBehavior class? One method could then be 
`Optional<Integer> getPostSuccessStatus(HttpStatusContext)`

with HttpStatusContext providing the resource in question (apiResponse.getEntity), the HttpMethod used, and potentially more? The optional would be used to allow multiple such classes with a first-win strategy? 

or maybe rather a more direct `ResourceAcceptedStrategy` with `Optional<Boolean> isProcessing(ResourceResponse)` that would set 202 instead if 201? This would hide the actual status handling.

**Comment by Sandmania** [comment]
This would be a great addition and would handle one case from the spec which isn't currently covered in Crnk (I think). But please bare in mind what the spec says about client generated ID. See http://jsonapi.org/format/#crud-creating-responses-201

**Comment by vicmosin** [comment]
I would rather go with more generic solution allows to specify the status code instead of true/false values (i.e. 202/201).

I would also think about extending `@JsonApiResource` as it can be per resource configuration, where default is 201

**Comment by remmeier** [comment]
sounds good to me. The generic solution could go into RepositoryInformation. The annotation might placed somewhere on the repository instead of the resource as only the server-side & repository is affected, not the resource itself. So far there are no (non-deprecated) annotations for repositories, but there might be one or the other use case. Annotations would then be translated  into a proper RepositoryInformation (as for any other annotation processing).

**Comment by remmeier** [comment]
There is now `HttpStatusBehavior` and `DefaultHttpStatusBehavior` to provide the desired customization.
