### ISSUE TITLE
Lombok support

### ISSUE THREAD

**Issue by vicmosin** [crnk-project/crnk-framework#223]
Any objections of using lombok in project?

**Comment by remmeier** [comment]
I hate the answer, but yes. It does a bit too much trickery for my taste. Which is still kind of ok. But then there are things like https://stackoverflow.com/questions/41520511/does-project-lombok-support-java-9 and issues with some IDEs (next to having to install it into the IDEs). But a proper solution like those Java data objects that may or may not come at some point would be really good to see.
