### ISSUE TITLE
crnk-spring + crnk-client does not support PATCH

### ISSUE THREAD

**Issue by OskarD** [crnk-project/crnk-framework#231]
crnk-spring contains `io.crnk.spring.client.RestTemplateAdapterProvider`, which is [the preferred HttpAdapter](https://github.com/crnk-project/crnk-framework/blob/db8c79ff51d0a6367524ef2ffe2c6d460966a0b8/crnk-client/src/main/java/io/crnk/client/CrnkClient.java#L119) in `CrnkClient`.

This implementation does not support the PATCH method, which will throw a `ResourceAccessException` with the following message:
> I/O error on PATCH request for "http://localhost:7027/api/v1/user/1": Invalid HTTP method: PATCH

I think this is detrimental to providing a starter kit for spring, since PATCH is part of the specification of JSON API.

But maybe I am missing some configuration here, is there any way to decide which implementation to use?

**Comment by remmeier** [comment]
I updated the docs::  http://www.crnk.io/documentation/#_setup_2. 

maybe there is a way for more support in the area to do this automatically. Not sure, maybe something that is aligned with what Spring Boot. Or improve RestTemplate to do auto detection.

**Comment by OskarD** [comment]
Thank you!

We actually just figured out the problem, and solved it like this:
```
        crnkClient.setHttpAdapter(OkHttpAdapter.newInstance());
```
