### ISSUE TITLE
POST to relationships triggers parent object validation

### ISSUE THREAD

**Issue by vicmosin** [crnk-project/crnk-framework#233]
It seems that [PR](https://github.com/crnk-project/crnk-framework/pull/164) introduced some unwanted side-effect. 
While trying to implement [add relations](http://jsonapi.org/format/#crud-updating-to-many-relationships) and parent object has some validation (for example, checks that object is already in DB) the `ValidationRepositoryFilter` triggers the validation and fails in that case. But this behavior is unwanted as the constraint violation in this case belongs to parent object and not to relation. 
The one solution might be to auto-validate only non-relationships objects..  i.e.
```
@Override
public JsonApiResponse filterRequest(final RepositoryFilterContext context, final RepositoryRequestFilterChain chain) {
	**if (context.getRequest().getRelationshipField() == null) {**
		if (context.getRequest().getMethod() == HttpMethod.POST || context.getRequest().getMethod() == HttpMethod.PATCH ||
					context.getRequest().getMethod() == HttpMethod.PUT) {
			Set<ConstraintViolation<Object>> violations = validator.validate(context.getRequest().getEntity());
			if (!violations.isEmpty()) {
				throw new ConstraintViolationException(violations);
			}
		}
	}

	return super.filterRequest(context, chain);
}
```

@remmeier any objections? Tests go through with that change

**Comment by remmeier** [comment]
yes, makes sense.
