### ISSUE TITLE
Possibility to hide a relation endpoint

### ISSUE THREAD

**Issue by kkamkou** [crnk-project/crnk-framework#234]
Please allow me not to expose the relation as the first level endpoint.

Example:
I have `/products/17/variants` implemented via two resources (`products` and `variants`), what I want is to disable/hide the `/variants` endpoint.

**Comment by Sandmania** [comment]
Could you just throw `UnsupportedOperationException` from all variants' `ResourceRepository` methods? As per spec, I don't think Crnk should hide a resource endpoint (at least not in the core implementation).

Other way of "disabling" could be by using crnk-security and disallowing access to variants, but I'm not quite sure how this would affect accessing it through a relation.

**Comment by remmeier** [comment]
one possiblity would be to define a relationship repository without a resource repository. In princpial doable except a small detail in CrnkBoot that needs to change (currently a registry entry is created for each resource repository, not for any relationship repositories).

An other thin one may or may not want is to have nested relationships like /products/17/variants/13/something. But I think the spec is silent about this and not sure whether to ever support that.

**Comment by kkamkou** [comment]
@remmeier, following your advice I'm trying to understand how it is implemented in crnk. Tests and docs are really poor to reveal this information.

The payload I have right now:
```java
    final String resourceType = "variants";
    RegistryEntryBuilder builder = ctx.newRegistryEntryBuilder();
    builder.resourceRepository().instance(new DynamicResourceRepository(resourceType));
    builder.resource().resourceType(resourceType);
    ctx.addRegistryEntry(builder.build());

    this.addRepository(new ProductsToVariants());

   // ProductsToVariants
   class ProductsToVariants
     extends ReadOnlyRelationshipRepositoryBase<Product, Serializable, Variants, UUID>
       implements ResourceFieldContributor {...}
```

But the next problem is in: `getResourceFields(ResourceFieldContributorContext context)`. This is executed for all resources. Therefore all of them have a new field from now on. Any tips?
