### ISSUE TITLE
Create crnk-gen-openapi to generate Swagger/OpenAPI definition

### ISSUE THREAD

**Issue by remmeier** [crnk-project/crnk-framework#237]
out of repositories. As a Swagger setup seems quite common/expected.

**Comment by remmeier** [comment]
could work quite similar to typescript generation, may even reuse the the gradle plugin

**Comment by julillosamaral** [comment]
I'm trying to do this. I don't know how much I will be able to advance and to integrate with crnk but at least I'll have a gist generating the swagger doc that can be integrated into crnk after.

The approach I'm doing is generate the doc using swagger-core (https://github.com/swagger-api/swagger-core). Any comments about this?

**Comment by remmeier** [comment]
that would be fairly awesome if you have time to get this done.

What would be necessary is to generate the swagger doc out of a crnk/JSONAPI endpoint. The problem with the swagger/JSON API combination is that JSON API already specifies tons of things which makes directly writing swagger documentation quite time consuming/uncessary. For JSON API all that would actually be needed is to specify the resources and relationships (much simpler than specifying the entire rest endpoint). Based on generated swagger doc clients may then do generation with swagger-core to access the JSON API endpoint.

similar to gen-typescript, crnk-meta can be the basis to perform the generation. Not sure whether swagger-core provides something to easily write a swagger doc file. To some degree the approach is similar to generating the swagger doc out of JAXRS/swagger annotations.

at some point we can refactor the typescript-generator plugin to a more generic plugin where typescript/swagger can be plugged in.

**Comment by remmeier** [comment]
(can help along the way)

**Comment by julillosamaral** [comment]
swagger-core specifies a set of classes to create the specification. My team and I have some experience on swagger specification but we generate it using PHP, doing it in Java will take me a bit more of time but I'm sure that we can do it.

For the moment I think the most difficult part is to get the information from crnk but I think I'll be able to do it. I'll let you know if I don't find a way to do something.

I'll check the typescript generator a bit more but as far as I understood it used some templates (am I wrong?). The approach I'm doing with swagger-core is a bit different, I'm instantiating all the classes and after that swagger-core has a method to dump those objects created into a JSON.

Regards,
Julio

**Comment by remmeier** [comment]
typescript generation takes MetaResource, MetaAttribute, etc. from crnk-meta and transforms it into a typescript meta model (TSInterface, etc.). Afterwards it is written to files with TSWriter.  So it may not be too unsimilar.

**Comment by remmeier** [comment]
there is now a ticket in JSON API (https://github.com/json-api/json-api/issues/1281) to establish a standard for schema definitions and based on that also do generation. So any input also welcome in that ticket.
