### ISSUE TITLE
Why was source.parameter renamed to source.legacy?

### ISSUE THREAD

**Issue by weaselmetal** [crnk-project/crnk-framework#241]
What was the driver for this renaming in an error response?
From a client point of view, it only breaks my error handling. As a client, I will be aware that I talk with an API that uses parameter naming that does not conform with jsonapi.org specs.
`source.legacy` in turn does not conform to jsonapi.org. Per jsonapi.org it must be `source.parameter`.
I think it's fine if it's always `source.parameter`, no matter the style of parameter names.

**Comment by remmeier** [comment]
yes, that is total wrong. Looks like an issue with the initial refactorings when setting up the project. But got unnoticed for quite awhile. Thx! 

It would actually be nice to make use of it more often. If parsing of any of the query parameter fails (such as in DefaultQuerySpecDeserializer), it should properly make use of it.

**Comment by weaselmetal** [comment]
Very nice! Just saw that you already [committed the change](https://github.com/crnk-project/crnk-framework/commit/8c72c8ee99a782754ccdcdeed41efe09f4688da6). Thanks a lot Remo!

**Comment by remmeier** [comment]
created https://github.com/crnk-project/crnk-framework/issues/244 to actually make use of it
