### ISSUE TITLE
QuerySpec duplicate uses same PagingSpec object

### ISSUE THREAD

**Issue by judos** [crnk-project/crnk-framework#247]
We run into an issue in our code because we duplicate QuerySpec a few times and modify the limit on these objects. However since the duplicate method of QuerySpec gives the reference to the same OffsetLimitPagingSpec object the limit is then changed for all QuerySpec objects.
This seems somehow undesirable.

```java
public QuerySpec duplicate() {
	QuerySpec copy = new QuerySpec(resourceClass);
->	copy.pagingSpec = pagingSpec;
	copy.includedFields.addAll(includedFields);
	copy.includedRelations.addAll(includedRelations);
	copy.sort.addAll(sort);
->	copy.filters.addAll(filters);
	Iterator<Entry<Object, QuerySpec>> iterator = relatedSpecs.entrySet().iterator();
	while (iterator.hasNext()) {
		Entry<Object, QuerySpec> entry = iterator.next();
		copy.relatedSpecs.put(entry.getKey(), entry.getValue().duplicate());
	}
	return copy;
}
```

Can someone update the method such that it returns a deep copy?
Thanks

**Comment by remmeier** [comment]
yes. all should be duplicated.

**Comment by remmeier** [comment]
cloned filter and sort spec as well

**Comment by remmeier** [comment]
note that PagingSpec.clone(...) is specified as default method, by default the same instance is returned. In v3 we can make it mandatory.
