### ISSUE TITLE
Mark relation as read-only

### ISSUE THREAD

**Issue by vicmosin** [crnk-project/crnk-framework#249]
Sometimes it might be required to mark the relation as read-only i.e. it shouldn't be updated from request. Couldn't find the way.. Any ideas?

**Comment by remmeier** [comment]
just noticed that @JsonApiField is actually not documented so far.

**Comment by vicmosin** [comment]
@remmeier Thanks. Btw I guess it's worth notice that `@JsonApiField` and `@JsonProperty(read/write)` are  mutually exclusive annotations, so maybe it's even better to define json-api-field as best practices, you know..

**Comment by vicmosin** [comment]
I guess I'll improve the docs if you're ok with prev statement..

**Comment by remmeier** [comment]
I guess so, it is also a bit more fine-grained. And can specify whether it is sortable/filterable.

At some point Jackson may also become exchangeable with other implementations (https://github.com/crnk-project/crnk-framework/issues/8), altough there is no hurry, just a general direction to not tie to much into it.
