### ISSUE TITLE
DefaultResourceInformationProvider: accept method must also check against the JsonApiResource.pagingBehavior attribute

### ISSUE THREAD

**Issue by daniel-deluca** [crnk-project/crnk-framework#256]
When building the ResourceInformation, the ModuleRegistry iterates through all the builders it has and takes the first builders that accepts the resourceClass. 
The fact is that the first builder is always (seems to be) the ResourceInformationProvider (DefaultResourceInformationProvider) that contains, as pagingBehavior the OffsetLimitPagingBehavior. 
The DefaultResourceInformationProvider, in the public boolean accept(Class<?> resourceClass) method must check, not only, if the resourceClass contains the JsonApiResource annotation but also if the pagingBehavior value/class of that annotation is in the pagingBehaviors Map.

**Comment by remmeier** [comment]
DefaultResourceInformationProvider must also be customizable, meaning having the possiblity to add further paging behaviors. That is already possible on the backend side through service discovery and CrnkBoot. But in CrnkClient offset/limit is still hard-coded. Maybe one should be able to register new paging behaviors through Module. That is something that works both on server and client side. Otherwise a CrnkClient.addPagingBehavior or something would be necessary.

**Comment by daniel-deluca** [comment]
Through the usage of adding new module I can add the pagingBehavior but my issue description still is valid. I'm changing the code of io.crnk.core.engine.internal.information.resource.DefaultResourceInformationProvider#accept in order to solve this.

**Comment by daniel-deluca** [comment]
Pull request done

**Comment by remmeier** [comment]
yes, the fix would work. But there is a catch that the DefaultResourceInformationProvider is internal API. I think maybe DefaultResourceInformationProvider and PagingBehavior are two quite independent classes. For this reason I think we should try to get those additional pagingBehaviors into the existing DefaultResourceInformationProvider instead of having to create new ones. On the backend side that is already possible. On the frontend side not yet. It might also become rather hard to track down the isuse of a missing pagingBehavior registration if non of the information provides accepts a resource. I think it would be sufficient to throw an exception? Or do you see another issue?

**Comment by daniel-deluca** [comment]
@remmeier : 
throwing an exception when non of the "Modules" are supporting the pagingBehavior specified class is OK for me as this means that there is a configuration/setup part missing.

With my fix in crnk-core, my client side code is just adding a new module with a specific ResourceInformationProvider that contains the pagingBehavior and adding the behavior class in the JsonAPIResource attribute.
```
    ResourceInformationProvider resourceInformationProvider = new DefaultResourceInformationProvider
                (key -> {
                    if (CrnkProperties.RESOURCE_SEARCH_PACKAGE.equals(key)) {
                        return "com.company.api.client";
                    } else {
                        return System.getProperty(key);
                    }
                },
                        ImmutableList.of(new PagingBehavior()),
                        new DefaultResourceFieldInformationProvider(), new JacksonResourceFieldInformationProvider());
        SimpleModule myModule = new SimpleModule("myModule");
        myModule.addResourceInformationProvider(resourceInformationProvider);
        
apiClient.addModule(myModule);

**Comment by remmeier** [comment]
let us do:
```
SimpleModule myModule = new SimpleModule("myModule");
myModule.addPagingBehavior(...)
```
to simplify the setup a bit. Those will then be added to the default DefaultResourceFieldInformationProvider.

At some point it would maybe also be nice to introduce support for ServiceDiscovery on the client side. So far it is server only.

**Comment by daniel-deluca** [comment]
@remmeier : Implementation done 
Although, I'm not sure about the "new NullPropertiesProvider()" usage in the DefaultResourceInformationProvider constructor used in the SimpleModule's addPagingBehavior method implementation.
If everything is OK with you, would it be possible to create a new official release of the framework ?
Thanks

**Comment by daniel-deluca** [comment]
@remmeier : I've tried to move the pagingBehaviors list to the ModuleRegistry in order to have both CrnkBoot and CrnkClient use that list but I'm stuck with the rest: what do you mean by "Both would feed that pagingBehavior list into one single ResourceInformationProvider.No further DefaultResourceInformationProvider would have to be configured " ??
I was not able to achieve that part.

Note: I've corrected the code based on your PR comments: Could you validate them and eventually do a release ? (This way I can use that official release on my side and do an official release of my Java Client using CRNK)
Note: I'm still willing to help doing PR on CRNK anyway
Thanks
Daniel

**Comment by remmeier** [comment]
looking at the codebase, I may would do:

- CrnkBoot.pagingBehaviors is obsoleted by aggregatedModule
- CrnkBoot.setupComponent must lookup paging behaviors from serviceDiscovery and also register to the module setup in that method.
- CrnkBoot.setupPagingBehavior would continue to honor those defaultPageLimit/maxPageLimit properties and contribute a OffsetLimitPagingBehavior if the aggregated module has no other paging behavior.
- CrnkBoot.addModules passes the paging behaviors from the aggregatedModule (as CrnkBoot.pagingBehaviors is deleted)
- CrnkClient.initJacksonModule would also make use of the pagingBehaviors out of aggregatedModule and similar to CrnkBoot add a OffsetLimtPagingBehavior if no other is found.

releases are not an issue, can be done as soon as merged.

**Comment by daniel-deluca** [comment]
@remmeier : OK got it finally (I think so ;-) ) I've updated the code.

**Comment by remmeier** [comment]
looks great I think. you even setup the service discovery in crnk-client, that is long overdue :-)

ModuleRegistry.pagingBehaviors may not be necessary, as a module can provide the same functionality. 

There is one small compilation issue in the test cases (the build fails), but otherwise we can then merge and release.

**Comment by daniel-deluca** [comment]
@remmeier : OK, removed the List<PagingBehavior> and fixed the Test that was not compiling.
Please validate, merge and release if OK 

Thanks

**Comment by nicolabeghin** [comment]
Is this related to `crnk-client` throwing exception 
> Exception in thread "main" io.crnk.core.exception.InvalidResourceException: CMSProduct not recognized as resource class, consider adding @JsonApiResource annotation
> 	at io.crnk.client.CrnkClient$ClientResourceRegistry.findEntry(CrnkClient.java:636)

if a custom `PagingBehavior` is specified in the JsonResource? 

    @JsonApiResource(type = "products", pagingBehavior = CMSPageSizePagingBehavior.class)
    public class CMSProduct

**Comment by remmeier** [comment]
yes, exactly

**Comment by remmeier** [comment]
(custom paging seems to get popular quite rapidly as it has just been released)

**Comment by remmeier** [comment]
Number/page size may something that could be added to crnk directly (if that is hiding beyond CMSPageSizePagingBehavior) next to offset/limit.
