### ISSUE TITLE
[crnk-jpa] included resource is not present in "included"

### ISSUE THREAD

**Issue by Eitraz** [crnk-project/crnk-framework#258]
In the latest version, when requesting a resource and multiple includes (for example http://127.0.0.1:9080/flow/1?include[flow]=supportLevel.name%2Ccustomer.name in a JUnit test), the last one is excluded from the _include_ array.

I can see that the SQL query is executed to select both supportLevel and customer in the example above, but only supportLevel is in the _include_array, but both ID's are present in the relationships object.
If I switch place to _?include[flow]=customer.name%2CsupportLevel.name_ instead instead, customer is present but supportLevel is not.

In my test both have the same ID.

It works as expected in version _2.3.20171118162238_ though.

**Comment by remmeier** [comment]
Hi, can you provide more information? in 2.5 the relationship handling has been refactored a bit to support the new @JsonApiRelationId. So it is likely that this change triggered an issue somewhere. But so far neither myself nor the test cases stumbled upon in it.

is "name" an entity as well that it is added to the include parameter?

both supportLevel and customer have the same id? but are of different type? and equals correctly tells them apart? does the issue popup with two different ids?

added some further examples to the test cases, but so far in crnk-core, not crnk-jpa. But I don't think any potential issue be related to crnk-jpa.

**Comment by remmeier** [comment]
I suspect it might be an encoding issue that arises in some but not all setups. Otherwise this would have gotten noticed quite a long time ago. I check some of our apps, and one showed the same issues. Potential fix is available in the 2.5.20180326154333 version.  If that was not it, I would require more infos.

**Comment by Eitraz** [comment]
Hi!

I tried a few different combinations (with and without .name, that is a field).

I will be able to provide a more detailed example in a day or two.

Thanks for fast feedback!

**Comment by remmeier** [comment]
not quite complete yet, I will look a bit further into it.

**Comment by remmeier** [comment]
seems to have cleared up now, the new RestTemplateAdapter in crnk-client makes use of the Spring RestTemplate (in spring settings). RestTemplate has some rather unusual behavior in terms of url encoding and now work around it (2.5.20180326220647) in the area. So you may want to look out for that. The other two adapters (apache http, okhttp) worked fine.

**Comment by Eitraz** [comment]
Version 2.5.20180326220647 works like a charm :)

**Comment by remmeier** [comment]
perfect, thx! I suspected as much, the RestTemplate was introduced with 2.4.x.
