### ISSUE TITLE
Get filter and sorting specs by attribute path

### ISSUE THREAD

**Issue by remmeier** [crnk-project/crnk-framework#26]
orignally from @ramblurr 

FilterSpec

For example this code:

      FilterSpec nameFilter = null;
        for(FilterSpec filter : spec.getFilters()) {
            if(filter.getAttributePath().get(0) == "name") {
                nameFilter = filter;
            }
        }

        if(nameFilter != null)
            return taskDao.findTasksByName(nameFilter.getValue());
        else
            return taskDao.findAllTasks();
Could be simplified to:

        String nameFilter = spec.getFilterByPath("name");
        if(StringUtils.isNotBlank(nameFilter))
            return taskDao.findTasksByName(nameFilter.getValue());
        else
            return taskDao.findAllTasks();
If this is the case then it should also be possible to fetch the orderings by path too e.g, spec.getOrderSpecByPath("task.project.createdDate)

Just imagine how that first code snippet would look if the was a nested filter param like filter[tasks][project][user][company][name]

**Comment by mohlek** [comment]
I'd like to have #45 on top :)

**Comment by remmeier** [comment]
done in the meantime
