### ISSUE TITLE
Make relation conditional

### ISSUE THREAD

**Issue by vicmosin** [crnk-project/crnk-framework#260]
It would be nice to have more programmatic control over resource i.e. for example, make relation conditional. Main usecase where I need this - crnk doesn't support inheritance but I have the hierarchy of POJO objects and have to define different json-api resource only because one of the resources in a pair has extra field or relation. Attribute can be removed by `@JsonIgnore`  but could not find similar for relation. 

In long term inheritance support should be added, but short-terms something like `@JsonApiField(visiable=false)` would help. @remmeier any ideas?

**Comment by remmeier** [comment]
where do you miss inheriance support? e.g. crnk-meta relies heavily on inheritance.

**Comment by remmeier** [comment]
e.g. MetaElement.java is the base class of many other resources and some of the relationships are sedined there.

**Comment by vicmosin** [comment]
I guess you got me wrong.. MetaElement and its children classes have their own `@JsonApiResource` definitions with unique names. What I need is to have the same `@JsonApiResource("XXX")` on 2 different POJOs where both of them has some parent POJO.

**Comment by vicmosin** [comment]
@remmeier But the question is still the same - is there any way where I can say to resource just not to generate the relation?

**Comment by remmeier** [comment]
yes, now I get it :-) 

maybe what you are looking for in this ticket would be support for @JsonInclude? https://www.concretepage.com/jackson-api/jackson-ignore-null-and-empty-fields

Having multiple @JsonApiResource("xxx") will currently cause all kinds of trouble. Not so sure about this. There is a strong reason not to separate them as different resources? Potentially JsonInclude and inheritance-as-is would be sufficient.

**Comment by remmeier** [comment]
yes, not so far

**Comment by vicmosin** [comment]
@remmeier well, in general I am not against respecting jackson annotations, I am just not sure whether it makes much sense as I remember the idea was to decouple serialization engine from crnk.. 
But still I believe #25 differs from my request as you event `@JsonInclude` can't really determine whether the relation must be removed or not as each relation might have different strategies to serialize it. I.e. lazy or eager.. 
What would the following mean:
```
@JsonInclude(NOT_NULL)
@JsonApiRelation(serialize = SerializeType.ONLY_ID)
private Relation rel;
```
As soon as rel is null -> do not serialize it? But what if I wanto to use a lazy serialization type?
So maybe it makes sense to introduce `SerializeType.NOT_NULL` or something?
