### ISSUE TITLE
UnrecognizedPropertyException: Unrecognized field "jsonapi"

### ISSUE THREAD

**Issue by nicolabeghin** [crnk-project/crnk-framework#265]
Hi everyone
on latest crnk (`io.crnk:crnk-client:2.5.20180326220647`) I'm experiencing an issue with what should be a valid JSONAPI feed.

![image](https://user-images.githubusercontent.com/2743637/38310440-dc3ade76-381c-11e8-9963-5aa5286445f9.png)
![image](https://user-images.githubusercontent.com/2743637/38310455-e5cd61e8-381c-11e8-8b14-f76751656800.png)

crnk fails on the `jsonapi` top-level member, is this supposed to be?

`Exception in thread "main" io.crnk.client.TransportException: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "jsonapi" (class io.crnk.core.engine.document.Document), not marked as ignorable (5 known properties: "links", "data", "errors", "included", "meta"])`

Model is a simple POJO like below:

    @JsonApiResource(type = "products")
    @JsonIgnoreProperties(ignoreUnknown = true)
    public class CMSProduct {
    
        @JsonApiId
        private Long id;
    
        private String name;
    
        private String description;
    
        private String photo_url;
    
        private boolean discontinued;
    [...]

A similar issue was reported in https://github.com/jasminb/jsonapi-converter/issues/170 (`jsonapi-converter` project)

`jsonapi` member is a valid JSONAPI specification: http://jsonapi.org/format/#document-top-level

> A document MAY contain any of these top-level members:
> - **jsonapi**: an object describing the server’s implementation
> - links: a links object related to the primary data.
> - included: an array of resource objects that are related to the primary data and/or each other (“included resources”). 

thanks
nicola

**Comment by nicolabeghin** [comment]
Temporary workaround by extending `CrnkClient`

    import com.fasterxml.jackson.databind.DeserializationFeature;
    import com.fasterxml.jackson.databind.ObjectMapper;
    import com.fasterxml.jackson.databind.SerializationFeature;
    import io.crnk.client.CrnkClient;
    import io.crnk.core.engine.url.ServiceUrlProvider;
    
    public class FixedCrnkClient extends CrnkClient {
    
        private ObjectMapper objectMapper;
    
        public FixedCrnkClient(String serviceUrl) {
            super(serviceUrl);
            this.objectMapper = new ObjectMapper();
            this.objectMapper.enable(SerializationFeature.INDENT_OUTPUT);
            this.objectMapper.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);
        }
    
        public FixedCrnkClient(String serviceUrl, ClientType clientType) {
            super(serviceUrl, clientType);
        }
    
        public FixedCrnkClient(ServiceUrlProvider serviceUrlProvider, ClientType clientType) {
            super(serviceUrlProvider, clientType);
        }
    
        @Override
        public ObjectMapper getObjectMapper() {
            return this.objectMapper;
        }
    }

**Comment by remmeier** [comment]
now supported, CrnkBoot.putServerInfo allows to set server information.
