### ISSUE TITLE
Unable to access CrnkFeature or DefaultQuerySpecDeserializer with CrnkClient

### ISSUE THREAD

**Issue by nicolabeghin** [crnk-project/crnk-framework#266]
Hi 
I don't understand if it's possible to extend the `CrnkClient` by use of `CrnkFeature` (while I see this is possible with server implementations).

Specifically, I need access to the `DefaultQuerySpecDeserializer` object.

thanks
nicola

**Comment by remmeier** [comment]
CrnkClient and CrnkFeature are usually quite separate, the former for the client, the later for the server. The client does not make use of DefaultQuerySpecDeserializer , but rather DefaultQuerySpecSerializer

**Comment by nicolabeghin** [comment]
sorry I wrote in a wrong way, I meant exactly `DefaultQuerySpecSerializer`. I'm currently looking around to see if it's possible to override it without recompiling `crnk-client`. Maybe you have any hint about this?

**Comment by remmeier** [comment]
yes, seems currently fairly hard-wired. That should change similar to CrnkBoot. Meaning CrnkClient has a setter to set a custom one.

**Comment by nicolabeghin** [comment]
Just committed a dumb PR if you want to merge it it can give some level of customization to the `CrnkClient`

**Comment by nicolabeghin** [comment]
@remmeier do you have experience with jitpack.io for importing the edited `crnk-client` module? 

```
<dependency>
    <groupId>com.github.nicolabeghin</groupId>
    <artifactId>crnk-framework</artifactId>
    <version>2.5.20180405160000</version>
</dependency>
```
I can only import the whole `crnk-framework` which leads to a number of `NoClassDefFoundError`

> Exception in thread "main" java.util.ServiceConfigurationError: io.crnk.core.module.discovery.ServiceDiscovery: Provider io.crnk.cdi.internal.CdiServiceDiscovery could not be instantiated
> 	at java.util.ServiceLoader.fail(ServiceLoader.java:232)
> 	at java.util.ServiceLoader.access$100(ServiceLoader.java:185)
> 	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:384)
> 	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
> 	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
> 	at io.crnk.core.module.discovery.DefaultServiceDiscoveryFactory.getInstance(DefaultServiceDiscoveryFactory.java:19)
> 	at io.crnk.core.module.discovery.FallbackServiceDiscoveryFactory.getInstance(FallbackServiceDiscoveryFactory.java:24)
> 	at io.crnk.client.CrnkClient.setupServiceDiscovery(CrnkClient.java:171)
> 	at io.crnk.client.CrnkClient.setupPagingBehavior(CrnkClient.java:183)
> 	at io.crnk.client.CrnkClient.<init>(CrnkClient.java:136)
> 	at io.crnk.client.CrnkClient.<init>(CrnkClient.java:115)

> Caused by: java.lang.NoClassDefFoundError: javax/enterprise/util/TypeLiteral
> 	at java.lang.Class.getDeclaredConstructors0(Native Method)
> 	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
> 	at java.lang.Class.getConstructor0(Class.java:3075)
> 	at java.lang.Class.newInstance(Class.java:412)
> 	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380)
> 	... 11 more
> Caused by: java.lang.ClassNotFoundException: javax.enterprise.util.TypeLiteral
> 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
> 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
> 	... 16 more

**Comment by nicolabeghin** [comment]
Done with

```
<dependency>
	<groupId>com.github.nicolabeghin.crnk-framework</groupId>
	<artifactId>crnk-client</artifactId>
	<version>2.5.20180405160000</version>
</dependency>

<dependency>
	<groupId>com.github.nicolabeghin.crnk-framework</groupId>
	<artifactId>crnk-spring</artifactId>
	<version>2.5.20180405160000</version>
</dependency>
```

**Comment by remmeier** [comment]
PR merged, closing ticket
