### ISSUE TITLE
JsonProperty annotations not respected in filters

### ISSUE THREAD

**Issue by philip-ince** [crnk-project/crnk-framework#267]
Crnk version: 2.5.20180314134358

Annotating a resource field with @JsonProperty("full-name") changes the name in GETs and POSTs, but trying to use it in a filter give the following error:

....?filter[full-name][LIKE]=puerto%

```
{
  "errors": [
    {
      "status": "500",
      "title": "Internal Server Error",
      "detail": "Cannot find an getter for com.example.Country.full-name",
      "meta": {
        "exception": "io.crnk.core.engine.internal.utils.PropertyException",
        "path": "/api/countries",
        "timestamp": 1522934913674
      }
    }
  ]
}
```

**Comment by remmeier** [comment]
so far that has not been added, but DefaultQuerySpecDeserializer and DefaultQuerySpecSerializer could do such a mapping (for sort, filter, field sets and inclusions).

For regular attributes that is already half-way in place. For example getAttributeType access ResourceField information holding both Java and JSON naming. For nested attributes, things get a bit more complicated as there is no ResourceField yet that does not hold the necessary mapping information.

**Comment by philip-ince** [comment]
Do you think it's a big change (the DefaultQuerySpecDeserializer/Serializer) part? I'm happy to give it a shot.

**Comment by remmeier** [comment]
- just for basic attributes it should be minor.
- for nested attributes we would have to model the nested object structures similar to ResourceInformation/ResourceField, maybe with BeanInformation/BeanField. Currently ResourceField has only getType and getGenericType. Might would need that type as BeanInformation. And BeanInformation would then give the possiblity to retrieve attributes by either Java or JSON name. 

This second part is a bit more elaborate. But a first basic version may not be overly hard. But I probably would be good to support both to have it consistent, meaning either do no mapping or map everything. A basic flavor of BeanInformation may not be overly hard, it does not have to be as elaborate as the entire ResourceInformation mechanism with providers, etc.

In the projects I worked on we rarely made use of renaming, so the current setup was sufficient. But would be good to support all.

**Comment by philip-ince** [comment]
I'll take a look at it.

**Comment by remmeier** [comment]
done
