### ISSUE TITLE
Metadata set in requests are ignored

### ISSUE THREAD

**Issue by systemfreund** [crnk-project/crnk-framework#270]
If a client attempts to create a resource that contains `meta` the server ignores it completely:
```
@JsonApiResource(type = "res")
class Res {

  @JsonApiMetaInformation
  private ResMeta meta;

  public static class ResMeta implements MetaInformation {
    private String metaField;
  }

}
```

Request body:
```
{
  "data" : {
    "type" : "res",
    "attributes" : {
    },
    "meta" : {
      "metaField" : "foobar"
    }
  },
}
```

Expected:
Instance of `Res` passed to repository `create`-method should have its `meta` field set properly.

Actual:
`Res.meta` is always `null`.

**Comment by remmeier** [comment]
Yes, would make sense to support this. ResourcePost and ResourcePatch within crnk-core should read and set those fields (similar to setAttributes).

**Comment by remmeier** [comment]
available on master or the mavenLatest repositoriy: https://bintray.com/crnk-project/mavenLatest/crnk-bom
