### ISSUE TITLE
Dependency on Guava

### ISSUE THREAD

**Issue by philip-ince** [crnk-project/crnk-framework#272]
It seems from previous Issues that the dependency on Guava has been removed, but I still see a dependency here https://github.com/crnk-project/crnk-framework/blob/1dca4f86912ab1cccd0c89579a7b44df067fe2cc/crnk-core/src/main/java/io/crnk/core/engine/internal/information/resource/DefaultResourceInformationProvider.java#L4

Is this supposed to be there?

**Comment by remmeier** [comment]
no that is an error, I removed it on the master branch.

that reflections library should probably removed from crnk-core as compileOnly dependency to avoid this kind of mistakes.

**Comment by remmeier** [comment]
does not really seem possible without causing compilation issues. Deprecated that mechanism in order to be able to remove it entirely in v3. guava, spring, etc. provide much better alternatives to that reflections discovery
