### ISSUE TITLE
Mixture of JPA and non-JPA resources

### ISSUE THREAD

**Issue by philip-ince** [crnk-project/crnk-framework#273]
Is there any way to mix JPA and non-JPA resources? I have a number of static data resources that I'd like to store in memory rather than in a DB (type B). Along side those I have other resources that are stored in the DB and have relationships to the previous type (type A).

However, when I start up crnk with these relationships, I get 

> Caused by: java.lang.IllegalStateException: java.util.NoSuchElementException: No value present
> 	at io.crnk.meta.MetaLookup.discover(MetaLookup.java:189) ~[crnk-meta-2.5.20180314134358.jar:na]
> 	at io.crnk.meta.MetaLookup.initialize(MetaLookup.java:159) ~[crnk-meta-2.5.20180314134358.jar:na]
> 	at io.crnk.jpa.JpaModule.setupModule(JpaModule.java:286) ~[crnk-jpa-2.5.20180314134358.jar:na]
> 	at io.crnk.core.module.ModuleRegistry.addModule(ModuleRegistry.java:126) ~[crnk-core-2.5.20180314134358.jar:na]
> 	at io.crnk.core.boot.CrnkBoot.addModules(CrnkBoot.java:339) ~[crnk-core-2.5.20180314134358.jar:na]
> 	at io.crnk.core.boot.CrnkBoot.bootDiscovery(CrnkBoot.java:186) ~[crnk-core-2.5.20180314134358.jar:na]
> 	at io.crnk.core.boot.CrnkBoot.boot(CrnkBoot.java:171) ~[crnk-core-2.5.20180314134358.jar:na]
> 	at io.crnk.spring.boot.v3.CrnkConfigV3.crnkBoot(CrnkConfigV3.java:98) ~[crnk-spring-2.5.20180314134358.jar:na]
> 	at io.crnk.spring.boot.v3.CrnkConfigV3$$EnhancerBySpringCGLIB$$e27d0aa7.CGLIB$crnkBoot$0(<generated>) ~[crnk-spring-2.5.20180314134358.jar:na]
> 	at io.crnk.spring.boot.v3.CrnkConfigV3$$EnhancerBySpringCGLIB$$e27d0aa7$$FastClassBySpringCGLIB$$ec28d0d3.invoke(<generated>) ~[crnk-spring-2.5.20180314134358.jar:na]
> 	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228) ~[spring-core-4.3.14.RELEASE.jar:4.3.14.RELEASE]
> 	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:358) ~[spring-context-4.3.14.RELEASE.jar:4.3.14.RELEASE]
> 	at io.crnk.spring.boot.v3.CrnkConfigV3$$EnhancerBySpringCGLIB$$e27d0aa7.crnkBoot(<generated>) ~[crnk-spring-2.5.20180314134358.jar:na]
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_161]
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_161]
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_161]
> 	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_161]
> 	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162) ~[spring-beans-4.3.14.RELEASE.jar:4.3.14.RELEASE]
> 	... 41 common frames omitted
> Caused by: java.util.NoSuchElementException: No value present
> 	at io.crnk.core.utils.Optional.get(Optional.java:35) ~[crnk-core-2.5.20180314134358.jar:na]
> 	at io.crnk.jpa.meta.internal.JpaMetaFilter.onInitialized(JpaMetaFilter.java:35) ~[crnk-jpa-2.5.20180314134358.jar:na]
> 	at io.crnk.meta.MetaLookup.initialize(MetaLookup.java:208) ~[crnk-meta-2.5.20180314134358.jar:na]
> 	at io.crnk.meta.MetaLookup.initialize(MetaLookup.java:204) ~[crnk-meta-2.5.20180314134358.jar:na]
> 	at io.crnk.meta.MetaLookup.discover(MetaLookup.java:184) ~[crnk-meta-2.5.20180314134358.jar:na]
> 	... 58 common frames omitted

This happens because type B isn't annotated with Embeddable, Entity or MappedSuperclass. Could we perhaps use a different MetaFilter if the field is annotated with Transient?

**Comment by remmeier** [comment]
how does entity A look like? does it have reference to type B? that would be unusable I think (at least in my apps). 

in general it should not be an issue. actually quite the contrary, relationships are possible between any kind of resource.

**Comment by philip-ince** [comment]
No it's a one way relationship - A -> B only

**Comment by remmeier** [comment]
I think the solution would be to make that field transient and add @JsonInclude. Ths way we could hide it from JPA but still in use by Jackson (and with that then also for Crnk). 

crnk-jpa maintains two meta models, one for JPA and one for resources. Tha failure above is in the JPA metal model. I think it goes away by adding the transient. Because there should be no MetaAttribute anymore of that relationship on the JPA layer.

Second part would be DefaultResourceFieldInformationProvider.isIgnored(). Currently it ignores anything transient. But it should further check @JsonInclude and then overrule the transient if present.

Both together then should work. A test case could be along the line of JpaQuerySpecEndToEndTest to have this officialy supported.

There are two alternatives that already work:
- crnk-example has a history example that works without touching the entities
- doing a DTO mapping and define the relationship on the DTO.

**Comment by mohlek** [comment]
`@jsoninclude` is not needed.
just annotate it with 
```java
    @Transient
    @JsonApiRelation(serialize = SerializeType.EAGER, lookUp = LookupIncludeBehavior.AUTOMATICALLY_WHEN_NULL)
    private ABC abc;
```

**Comment by remmeier** [comment]
are you sure? I don't think it will get passed beyond that DefaultResourceFieldInformationProvider.isIgnored

**Comment by mohlek** [comment]
Well i use it that way and it works

**Comment by remmeier** [comment]
right since @Transient comes from JPA rather than the general "transient". there was minor issue with the that it was still picked up by the meta module mechanisms. But that did not seem to cause any issues. Added a test case and documentation for it (and ignored it in the meta model).

**Comment by remmeier** [comment]
thx!
