### ISSUE TITLE
totalResourceCount in meta is null if not using pagination

### ISSUE THREAD

**Issue by juniorhamish** [crnk-project/crnk-framework#277]
If the request url for a collection does not include a page[limit] or page[offset] then the totalResourceCount is not set. In this case the meta section of the response contains:

`"meta": {
    "totalResourceCount": null
}`

I think the totalResourceCount should always be set even if not using pagination (or should be excluded from the response body).

The place where this happens in the code is, InMemoryEvaluator.eval

**Comment by remmeier** [comment]
would be a good case to modify the null/empty handling of Jackson (https://stackoverflow.com/questions/16089651/jackson-serialization-ignore-empty-values-or-null).

**Comment by juniorhamish** [comment]
Does that mean you think it should not be included in the response if we are not using pagination rather than including it but with the value set?

**Comment by remmeier** [comment]
I would say so. If no paging is requested it does not make to much sense to include it?

**Comment by remmeier** [comment]
done accordingly, release available shortly
