### ISSUE TITLE
Typo in docs?

### ISSUE THREAD

**Issue by StevenPTurner** [crnk-project/crnk-framework#280]
On the docs at http://www.crnk.io/documentation/#_jsonapilinksinformation it gives an example of linking using @JsonApiLinksInformation, a new class is created that implements the MetaInformation interface, it looks like this is a typo and should be implementing the LinksInformation instead.

**Comment by remmeier** [comment]
indeed, ideally the documentation would directly import a live/working source snippet. Obvisiouly that is not the case here. This  has not been possible in the past, but is now, and things move slowely into that direction.
