### ISSUE TITLE
crnk + SpringBoot + Postgresql 

### ISSUE THREAD

**Issue by 3mendous** [crnk-project/crnk-framework#282]
Hello,
I can't understand how to connect my RestController to db, how i can send queries to db and get it's response?
I tried some ways like this

```
for (RegistryEntry entry : resourceRegistry.getResources()) {
            entry.getResourceRepositoryFacade().findAll(new QuerySpec(Test.class));
        }
```
Execution always gets to my repository, as I understood I need to realize findAll method to send queries to db, but i can't find the way to do this. Could somebody help my with this issue?

**Comment by remmeier** [comment]
Hi, what are you trying to achieve? usually you don't have to make use of the resourceRegistry/facade.

**Comment by 3mendous** [comment]
I'm just trying to create simple rest controller with crud operations using db. I found this article https://www.codenotfound.com/json-api-crnk-spring-boot-example.html, and didn't find examples with db (except mongo in this repo)

**Comment by remmeier** [comment]
https://github.com/crnk-project/crnk-example shows some more things. maybe it is also worthwhile to add crnk-home to get a listing of available resources.

**Comment by remmeier** [comment]
do you need programmatic access to the JPA-related repositories somewhere in your code? you do not have to write any controllers or something. you can just do a crnk-jpa setup in the example applications and make use of them by calling the apprioriate urls. 

Thinks like https://github.com/3mendous/json-api-elide/blob/master/src/main/java/ru/sbt/qa/Controller.java are all done by crnk-core and crnk-jpa and are not necessary. The only thing necessary is setting up and registering the JpaModule. And if you have advanced customizations, maybe make use of, for example, the RepositoryDecoratorFactory.

**Comment by remmeier** [comment]
for basic CRUD access, 10 lines should be sufficient. If there is more, likely something is wrong with the setup.

crnk explicitly tries to free people from having to define all those annotations, path mappings, etc. (the same holds for https://github.com/3mendous/JPA/blob/master/src/main/java/ru/sbt/qa/controller/Controller.java similar to the other controller referenced above, also not necessary in crnk)

**Comment by remmeier** [comment]
feel free to reopen if there are more questions
