### ISSUE TITLE
Alternative pagination is hard to use - should become the global default

### ISSUE THREAD

**Issue by weaselmetal** [crnk-project/crnk-framework#284]
By now it should be possible to write your own implementation of `PagingBehavior`, which I did.
However, my support for `page[size]` and `page[number]` is not really picked up well.

My implementation is indeed used by crnk. It's a spring bean that crnk can get hold of via the nice `ServiceDiscovery` interface.
But, crnk stops creating pagination links in the response after registering this behavior. The reason is rather complicated.

The `JsonApiResource` annotation specifies that the default `pagingBehavior` is `OffsetLimitPagingBehavior.class`.
When the `ResourceInformation` for a resource is created, the following happens:
From the registered paging behaviors (only my custom one present), one is picked that matches the pagingBehavior of the annotated resources. [see this change](https://github.com/crnk-project/crnk-framework/commit/71a9f4c9655bf5fc77f5061b29ba0323e2d76bd2#diff-1dcde304f2fcd554078bc512586d5149R87)

Since it's my registered custom pagination versus the default OffsetLimitPagingation, on the `ResourceInformation` the `pagingBehavior` is set to null.
And finally [this check](https://github.com/crnk-project/crnk-framework/commit/71a9f4c9655bf5fc77f5061b29ba0323e2d76bd2#diff-742387973881b94147ab66bc183fdf3bR178) **stops crnk from writing any pagination links**.

I would have expected, that registering a custom pagination behavior ensures that this becomes the global default. That's not the case. I could go through all 80+ exposed resources and add the custom pagination behavior as desired behavior, but that ain't cool. In general, I'd want the same behavior for whole API. Maybe with the option to change it to something else where needed.

@vicmosin would it be possible to make a custom pagination behavior the new default behavior for the entire API?

**Comment by remmeier** [comment]
too bad null is not a legal annotation value. I guess a DefaultPagingBehavior class is necessary that forwards to the global default.

**Comment by remmeier** [comment]
already a number of annotation values go with a "DEFAULT" enum constant.

**Comment by weaselmetal** [comment]
I think I have a solution. A noop-PagingBehavior as default, that will always get replaced by the first registered paging behavior should cut it. Gonna give it a try.

**Comment by remmeier** [comment]
forwarding of DefaultPagingBehavior to the default implementation (available from the module registry) might be more transparent compared to replacing the implementation, depending on what is meant by replacing.

**Comment by weaselmetal** [comment]
// cross check if desired resource paging behavior is a registered behavior, error out if not.
    // if no behavior is set for the resource, we pick the first from registered behaviors.
    java.util.Optional<PagingBehavior> optPagingBehavior;
    if (!pagingBehaviorType.equals(VoidPagingBehavior.class)) {
        optPagingBehavior = pagingBehaviors.values().stream()
                        .filter(it -> pagingBehaviorType.isInstance(it))
                        .findFirst();

        if (!optPagingBehavior.isPresent()) {
            throw new IllegalStateException("paging behavior not found: " + pagingBehaviorType);
        }

    } else {
        optPagingBehavior = pagingBehaviors.values().stream().findFirst();
    }

That's what I currently have.

**Comment by remmeier** [comment]
I was hoping to avoid adding logic to the engine part, it should get simpler, not more complex :-)
So if somebody looks at that new paging behavior (DefaultPagingBehavior?) he knows what is going on in there instead of having to look at the crnk engine to see how it gets replaced by something different. In the future it then may also open up more possibilities how that forwarding is done.

**Comment by weaselmetal** [comment]
I'll check if I could get the forwarding implemented. I understand your idea at least.

**Comment by weaselmetal** [comment]
Hum, one drawback is, that when you debug, you'll only see that the pagingBehavior is of type `DefaultPagingBehavior`, and you'd always have to check what it actually delegates too. So this is more obfuscating than helpful, from a framework user point of view. With the current version, it would say that 
responseResourceInformation.getPagingBehavior() is a `OffsetLimitPagingBehavior`, or, in my case, `PageSizeAndNumberBehaviour`.

**Comment by vicmosin** [comment]
The main reason why we have built-in paging behaviour is because @remmeier did not want to destroy existing consumers logics..

**Comment by weaselmetal** [comment]
The way it's currently implemented, it should be compatible with all existing projects out there @vicmosin

**Comment by vicmosin** [comment]
I don't say it's not.. I am just kinda answer the original question.. why we have it from the scratch i.e. from PR merge :)
