### ISSUE TITLE
JacksonModule registers incomplete pagingBehaviors

### ISSUE THREAD

**Issue by weaselmetal** [crnk-project/crnk-framework#295]
This is kind of a hen and egg problem.
Adding a module correctly depends on having pagingBehaviors registered already.
Otherwise `io.crnk.core.engine.internal.jackson.JacksonModule#setupModule` creates a new `DefaultResourceInformationProvider` instance with missing behaviors.
On the other hand, a module should be able to register new pagingBehavior. But it will lack any behavior that is added through modules that are added later on.
At the time when `io.crnk.core.engine.internal.information.resource.DefaultResourceInformationProvider#build(java.lang.Class<?>, boolean)` is called, the object may lack some registered paging behaviors (through modules) and fail.

I think the reason these tests worked:
https://travis-ci.org/crnk-project/crnk-framework/builds/370068790?utm_source=github_status&utm_medium=notification
was due to another bug / mishap: The serviceDiscovery is set to `ReflectionsServiceDiscovery(packageName)`, which picked up all the classes in the same package, including the `CustomOffsetLimitPagingBehavior`. Which I doubt was the intention. Maybe it was, anyway it hid the fact that it's not registered through the modules.

I haven't fully understood the entire bootstrapping process, but registering paging through modules behavior seems flawed. Is it not enough that any `PagingBehavior` is correctly registered through the `ServiceDiscovery`?

**Comment by weaselmetal** [comment]
If you want to see for yourself, then move `CustomOffsetLimitPagingBehavior` from package `io.crnk.core.queryspec.repository` to `io.crnk.core.queryspec.pagingspec` on master branch. Same tests will fail.

**Comment by weaselmetal** [comment]
The source of the problem is in `JacksonModule` where this code

    @Override
    public void setupModule(ModuleContext context) {
        objectMapper.registerModule(createJacksonModule(serializeLinksAsObjects));

        DefaultResourceFieldInformationProvider defaultFieldProvider = new DefaultResourceFieldInformationProvider();
        ResourceFieldInformationProvider jacksonFieldProvider = new JacksonResourceFieldInformationProvider();

        // TODO move somewhere else and make use of a SerializerExtension
        context.addResourceInformationBuilder(new DefaultResourceInformationProvider(
            context.getPropertiesProvider(),
            pagingBehaviors,
            defaultFieldProvider,
            jacksonFieldProvider));
    }

is executed before all modules had a chance to register their paging behavior.

**Comment by remmeier** [comment]
the following code sipped in DefaultResourceInformationProvider should potentially be avoided:

```
this.pagingBehaviors = new HashMap<>(pagingBehaviors.size());
for (int i = 0; i < pagingBehaviors.size(); i++) {
this.pagingBehaviors.put(pagingBehaviors.get(i).getClass(), pagingBehaviors.get(i));
}
```

The ModuleRegistry should provide the paging behaviors with a data structure already suitable for the consumers (this information provider). That data structure should also be up-to-date so that the order of execution does not matter. For other registrations similar things are done, for example ResourceFilterDirectory.

But also agree that the information provider should be moved out of the Jackson module. Altough it should be possible to register ResourceFieldInformationProvider from the JacksonModule. but since Jackson is the only supported serializer, that currently does not matter much.

**Comment by weaselmetal** [comment]
Please check out this PR https://github.com/crnk-project/crnk-framework/pull/296
Don't really have an idea why the brave module tests fail atm.

**Comment by remmeier** [comment]
the client lacks that InformationProvider (or is registered to late). I suspect that will popup in various places. Maybe just having a PagingBehaviorDirectory provided by ModuleRegistry would be simpler/more robust.

**Comment by weaselmetal** [comment]
> the client lacks that InformationProvider
that's the case, yes. CrnkClient also depended on `JacksonModule` to construct a `ResourceInformationProvider`. CrnkClient and CrnkBoot share some behavior it seems.
`JacksonModule` is not instantiated in too many places, which is good.

**Comment by weaselmetal** [comment]
@remmeier I'll turn this 

    SimpleModule resourceInformationProviderModule = new SimpleModule("resourceInformationProvider") {

        @Override
        public void setupModule(ModuleContext context) {

            DefaultResourceFieldInformationProvider defaultFieldProvider = new DefaultResourceFieldInformationProvider();
            ResourceFieldInformationProvider jacksonFieldProvider = new JacksonResourceFieldInformationProvider();

            // at this point in time, all paging behaviors from other modules should be
            // registered with the moduleRegistry
            context.addResourceInformationBuilder(new DefaultResourceInformationProvider(
                    context.getPropertiesProvider(),
                    moduleRegistry.getPagingBehaviors(),
                    defaultFieldProvider,
                    jacksonFieldProvider));

            super.setupModule(context);
        }
    };

into a standalone module that will be added in CrnkBoot and CrnkClient.

**Comment by weaselmetal** [comment]
Merged into master. Closing this issue.
