### ISSUE TITLE
Support page number/limit next to offset/limit

### ISSUE THREAD

**Issue by remmeier** [crnk-project/crnk-framework#306]
Implementation should be compatible to OffsetLimit paging strategy to let repositories be implemented with one type in mind and also work with others. For this the paging spec implements both types of methods and calculate one from the other. alternatively we may introduce a mapping somewhere in the request processing, but that may be more complicated/not worthwhile to add.

**Comment by philip-ince** [comment]
I'll take a look at this

**Comment by remmeier** [comment]
done
