### ISSUE TITLE
JPA and auto-generated id

### ISSUE THREAD

**Issue by civilu** [crnk-project/crnk-framework#311]
Hi,

I would expect that, when I create a resource backed by a JPA entity with a `@GeneratedValue` id, Crnk would use whatever JPA generates as the resource id. However, that does not seem to happen. So, either I'm misunderstanding how things should work, or I do, but I'm not using crnk-jpa properly, or there's a bug...

I'm using OpenJPA and Jersey on Jetty, if that helps with anything.

I'm setting up my repository like so:
```java
JpaRepositoryConfig<Contact> contactRepository = JpaRepositoryConfig.builder(Contact.class).build();
jpaModuleConfig.addRepository(contactRepository);

JpaModule.createServerModule(jpaModuleConfig, Main.entityManager, transactionRunner);
```

My `Contact` resource is annotated to auto-generate the id:

```java
@Entity
@JpaResource(type = "contact")
public class Contact {
  @JsonApiId
  @Id 
  @GeneratedValue 
  private long id;

  @Column
  private String name;

  public long getId() { return id; }
 
  public void setId(long id) { this.id = id; }

  public String getName() { return name; }

  public void setName(String name) { this.name = name; }
}
```

No problem getting the contact resource:

```
GET /api/contact HTTP/1.1
Accept: application/vnd.api+json

HTTP/1.1 200 OK
Content-Type: application/vnd.api+json; charset=utf-8
{
  "data" : [ ]
}
```

But, when trying to create one:

```
POST /api/contact HTTP/1.1
Accept: application/vnd.api+json
Content-Type: application/vnd.api+json
{
  "data": {
    "type": "contact",
    "attributes": {
 	  "name": "Contact 1"
    }
  }
}

HTTP/1.1 500 Internal Server Error
Content-Type: application/vnd.api+json; charset=utf-8
{
  "errors" : [ {
    "status" : "500",
    "title" : "INTERNAL_SERVER_ERROR",
    "detail" : "java.lang.IllegalStateException: id not available for entity Contact@715ef0b7"
  } ]
}
```

What I see in debug is that `JpaEntityRepository#saveInternal` persists my entity, then immediately tries to retrieve the id. Since this is performed inside a transaction which has not been committed yet (the control passes to my implementation of `TransactionRunner` later), there's no id to be retrieved and the exception is thrown.

That makes me think that my (rather naive) implementation of `TransactionRunner` may be the culprit:

```java
class SimpleTransactionRunner implements TransactionRunner {
  @Override
  public <T> T doInTransaction(Callable<T> callable) {
    EntityTransaction transaction = Main.entityManager.getTransaction();	
    transaction.begin();
		
    try {
      return callable.call();
    } catch (Exception e) {
      transaction.rollback();
      throw new IllegalStateException(e);
    } finally {
      if (transaction.isActive()) {
        transaction.commit();
    }
  }
}
```

**Comment by remmeier** [comment]
fairly certain that it works for hibernate. maybe a flush should be triggered, at least for generated ids. maybe not else for performance reasons.

**Comment by civilu** [comment]
Just tested with Hibernate and I confirm it works.

Tried adding a flush in `JpaEntityRepository#saveInternal` just to see that it would work, but ran into further OpenJPA weirdness, which I haven't figured out yet. 

I will report back when I get some results.

**Comment by remmeier** [comment]
personally I prefer Hibernate over OpenJPA. But would not mind having tests in crnk-jpa to check compatiblity with OpenJPA as well. One could execute the same tests as for Hibernate.

**Comment by remmeier** [comment]
closed due to inactivity
