### ISSUE TITLE
Validation module is outdated in maven repository

### ISSUE THREAD

**Issue by KrasimirProdanov** [crnk-project/crnk-framework#319]
https://mvnrepository.com/artifact/io.crnk/crnk-validation

```
<!-- https://mvnrepository.com/artifact/io.crnk/crnk-validation -->
<dependency>
    <groupId>io.crnk</groupId>
    <artifactId>crnk-validation</artifactId>
    <version>2.6.20180430100742</version>
    <scope>test</scope>
</dependency>
```
Should be `2.6.20180430102904` to match other modules

**Comment by remmeier** [comment]
have to check the sync, but you may go with jcenter rather than mqven central. the later has shown to be rather unreliable/slow.
