### ISSUE TITLE
simplify setup/configuration

### ISSUE THREAD

**Issue by remmeier** [crnk-project/crnk-framework#323]
done:
- protect against null value from repository.getResourceClass
- simplify configuration setup in typescript generation (avoid package definitions by default) 
- provide few INFO log messages with the basics (discovered repositories, etc.)
- clear error message when accessing invalid filter attribute, e.g. filter[active][equals] instead of filter[active]
- remove Typescript package generation support (can be done manually if really needed)
- warn in log if jsonapi repository is accessed without jsonapi content type
- null resource returned by repository.create should get better error message in controller
- CrnkSecurityAutoConfiguration add condition on class for spring security
- setup minimal spring example
- make web-path-prefix optional for spring-based apps
- provide warning if security disables everything for a request
- protect against invalid configuration in security module

open:
- JpaModule.getRepository to have quick access to JPA repositories
- validate JpaRepositoryConfig
- protect against invalid DTO mapping configuration
- create test kit to check all links on endpoint
- protect against referencing resources as non-relationships
- protect against relationship repositories having no match
- protect against decorators having no match
- protect against missing resources/relationships => fail instead of giving a warning
- provide TRACE logging
- provide error message for invalid access to Optional.get/Nullable.get
- get entity-based QuerySpec in JPA module
- backoff in expose all if already registred and give warning
- simplify mapping of QuerySpec mapping with utility and setters
- check date parsing in filter values and error messages when wrong format
- QuerySpec Java example in filtering, sorting
- clarify ResourceRepository.findAll(ids, querySpec)
- clarify filter by multipel values

**Comment by yuvalbo** [comment]
Add logging to `io.crnk.core.engine.internal.information.DefaultInformationBuilder` and in general when `PreconditionUtil` is used, full traceability is required (e.g. validated resource and field names)
