### ISSUE TITLE
JpaModule doesn't fetches @OneToOne relationship

### ISSUE THREAD

**Issue by belovaf** [crnk-project/crnk-framework#351]
I have 2 entities: `Parent` and `Child`.
`Child` is a owner of `@OneToOne` relationship:
```
class Parent {
    @OneToOne(mappedBy="parent")
    public Child getChild() { return child; }
    ...
}
class Child {
    @OneToOne
    public Parent geParent() { return parent; }
    ...
}
```

Then I create Parent with id=1 and related Child with id=1.

`/crnk/api/v1/child/1/parent` correctly fetches Parent with id=1.
`/crnk/api/v1/parent/1/child` return null

If i change relationship types to `@OneToMane` and `@ManyToOne` all works as expected.

**Comment by belovaf** [comment]
Probably bug is in JpaRelationshipRepository#findOneTarget.
This method returns null, when expected exactly one child object.

**Comment by remmeier** [comment]
If so, would have to be at that place yes. The JPA/Hibernate/... may give a hint of what is wrong with the query.

**Comment by remmeier** [comment]
https://github.com/crnk-project/crnk-framework/issues/438 introduced a new mechanisms for relationships handling and added a variety of further one-to-one tests. In some areas it now works around JPA limitations like allowing only updates from one side (the mappedBy side).
