### ISSUE TITLE
DefaultQuerySpecUrlMapper enforceDotPathSeparator using just for parse.

### ISSUE THREAD

**Issue by dvtelles** [crnk-project/crnk-framework#353]
Hi, 

i was looking the code that serializes a QuerySpec to a Url and i got this question.
In DefaultQuerySpecUrlMapper, there is this property called enforceDotPathSeparator.
I tought it would use brackets like "[resource][sub-resource][field]" when serializing a QuerySpec to a Url but it doens't. 
Later i checked that it's only used when parsing filter parameter name.
Shoudn't be used in the url serialization too?

**Comment by remmeier** [comment]
yes, it should. the serializer/deserializer has just a few weeks ago been merged into the url mapper to allow this kind of alignments. Help would be more than welcomed.

**Comment by dvtelles** [comment]
Sure. 
I just have another question then. If i set enforceDotPathSeparator to false,
does the framework supossed to throw an excpetion in case i provide a url using dot notation?

**Comment by remmeier** [comment]
sorry, has been a while since I looked in that area. Actually everything is fine but the documentation is not specific enough. I updated that:

http://www.crnk.io/releases/latest/documentation/#_url_mapping

However, it would be desirable if the JSON API specification is a bit clearer about this things. There are some tickets open in the area, like https://github.com/json-api/json-api/issues/1272 and https://github.com/json-api/json-api/issues/1175. So so far primarly the dotted notation is recommended, but that is just a guess due to the lack of a spec. Some noise/help in that area would be helpful to move forward with the spec.

**Comment by dvtelles** [comment]
In my humble opinion, i do think that using dot notation is better than using brackets cause of the problem of the name a resource clashes with the attribute name.

I'm asking all of this, cause i'm only using the CnrkClient to call a JsonAPI that is using Katharsis as backend.

I thought if i set the enforceDotPathSeparator to false, the client would serialize the url to be called with brackets.

The backend service in calling with CrnkClient is using Katharsis Framework. It doesn't support dot notation like this:
`http://localhost/api/resource?filter[resource][subresource.code][EQ]=143`
It only allows dot notation without the resource like:
`http://localhost/api/resource?filter[subresource.code][EQ]=143`

Thats why i'm asking if setting the enforceDotPathSeparator to false would force the client to generate the url with brackets notation.

If that´s the case, i'm glad to submit a pull request with that little tweak. 

Thanks for your attention.

Ps.: Indeed the json:api specification is a little vague.

**Comment by remmeier** [comment]
no it only accepts "Katharsis-style" requests, but cannot create those. If you would like to have that, you could adapt and register a modified url mapper accordingly.

For crnk the json api specification should be pushed a bit to not end-up with too many variations.

**Comment by dvtelles** [comment]
I already did it. I was just asking if crnk is supposed to do that, and if it was the case submit the code.

Anyway, i'm closing this issue. Thanks for your attention.

**Comment by remmeier** [comment]
lets wait a bit and check whether the spec is arriving before implementing additional url formats. But if you had trouble customizing the url mapper, changes in that regard would be interesting to have in any case.
