### ISSUE TITLE
@JsonProperty is not working for  includeFields option if MapJsonName=true

### ISSUE THREAD

**Issue by Hira-Mahmood** [crnk-project/crnk-framework#362]
I am using  @JsonProperty in URL and set MapJsonName as TRUE 
[ DefaultQuerySpecUrlMapper.setMapJsonNames(true) ] 
after this Filter option is working fine but includeFields option is not working properly its not resulting fields whose JsonName are passed.
Example URL : 
http://localhost:8080/contacts/3560000007775497?fields[contacts]=reference-id,contact-classification-code,contact

Output:
{
  "data" : {
    "id" : "10001IN-3560000007775497-MO1",
    "type" : "contacts",
    "attributes" : {
      "contact" : "977178476"
    },
    "links" : {
      "self" : "http://localhost:8080/contacts/10001IN-3560000007775497-MO1"
    }
  }
}

In above example reference-id and contact-classification-code are fields are missing.

using crnk version =  2.6.20180430102904 
[ContactResource.txt](https://github.com/crnk-project/crnk-framework/files/2179963/ContactResource.txt)

**Comment by remmeier** [comment]
DefaultQuerySpecUrlMapper needs to be checked. But everything should run through the pathResolver.

**Comment by remmeier** [comment]
ah perfectly right. A test should be added to that IncludeLookupSetterBaseTest. e.g. based on Schedule.followupProject that has been renamed. 

Personally I barely used it, so there might be a gap as it seems. In general it would be great to have a bit more flexiblity about naming, e.g. in Java, Json and URL.

**Comment by remmeier** [comment]
fixed
