### ISSUE TITLE
CrnkClient BulkRelationshipRepositoryV2 support

### ISSUE THREAD

**Issue by vicmosin** [crnk-project/crnk-framework#367]
Could not find any support for that repo type. Any insights whether it makes sense to have it? Or reasons why it's not done yet?
Thank you

**Comment by remmeier** [comment]
yes, should maybe be mentioned. It is only internally to perform lookups faster (1 instead of n queries). Not specified by JSON API to be available as URL.

**Comment by remmeier** [comment]
any kind of inclusion with QuerySpec.includeRelation will do

**Comment by vicmosin** [comment]
@remmeier Could you please provide an example?I don't really get what you mean

**Comment by remmeier** [comment]
```
CrnkClient client = new ...
ResourceRepositoryV2<X,Y> repo = client.getRepositoryForType(...)
Queryspec querySpec = new QuerySpec(X.class)
querySpec.includeRelations(Arrays.aslist("myrelationship")
repo.findAll(querySpec)
```

to compute the inclusions of the relationship ît will make use of the bulk repository

**Comment by vicmosin** [comment]
Will this call make internal call to an appropriate relationshiprepoV2 ?

**Comment by remmeier** [comment]
yes, if the X resource repository does not return the relationships directly and has the lookup behavior configured accordingly.
