### ISSUE TITLE
CrnkClient creates its own ObjectMapper instance

### ISSUE THREAD

**Issue by d80harri** [crnk-project/crnk-framework#368]
On the server you can freely configure your own ObjectMapper. However, CrnkClient creates its own ObjectMapper with "new" in the constructor.  Therefore the mapping might work differently on client and server. This might even result in an exception when trying to deserialize a response from the server. 

Solution: Add an additional constructor in CrnkClient that uses an instance of an ObjectMapper.

**Comment by d80harri** [comment]
Could someone please add me as a member to this project, so I can add a pull request for this one? :)

**Comment by mohlek** [comment]
You don't have to be a member. Create a fork. Create a branch and then
create a pull request

Harald Bittermann <notifications@github.com> schrieb am Mo., 16. Juli 2018,
16:38:

**Comment by remmeier** [comment]
I think we should rather go with a setter rather than the constructor. The default ObjectMapper should then be created in CrnkClient init with not specified otherwise. The default should also be created when accessing getObjectMapper() to maintain backward compatiblity. once the default is initialized, it should not be possible to use the setter anymore to prevent from multiple ObjectMappers beeing used simultaenously.

**Comment by d80harri** [comment]
I don't really get what you mean with "The default ObjectMapper should then be created in CrnkClient init **with (if?) not specified otherwise**". How would you specify it otherwise if not with a constructor parameter?

**Comment by mohlek** [comment]
why dont use a `createObjectMapper()` which can be overridden?

**Comment by d80harri** [comment]
That would rather be the last option I consider. I wouldnt want to force a caller to extend an object to configure its behaviour. 

Whats the problem with the constructor in first place?

**Comment by mohlek** [comment]
Basically most of our ( crnk ) classes are designed that way. Thats why I
suggested it.

**Comment by remmeier** [comment]
I meant that if setObjectMapper(...) is not called, then a default one will be created in init(...) or if requested by getObjectMapper(...). At that point the ObjectMapper cannot be changed anymore.

**Comment by d80harri** [comment]
So the default ObjectMapper will not be created in the constructor but in init() (if and only if objectMapper is null). init() will be called by getObjectMapper(). And setObjectMapper will throw an exception if initialized==true. 

Since objectMapper is used in the constructor to build a ClientDocumentMapper, the same has to be done with getDocumentMapper. Right?

**Comment by remmeier** [comment]
sorry I missed your last comment: CrnkClient.getObjectMapper() should only create the default ObjectMapper if necessary. It should not initialize the client completely.

An alternative approach could be to start introduce a CrnkClientConfig to make the contract clearer.

**Comment by iamareebjamal** [comment]
This limit the capabilities of the library a lot. Failure in Kotlin projects, on unknown properties and several other problems. There should be an option to pass it through constructor. It does not break any backward compatibility and is the preferred way. And yes, there should be a Builder like in Retrofit and OkHttp for customisation, but that doesn't change the fact that there still needs to be constructor injection of Object Mapper.

**Comment by remmeier** [comment]
we should address it fianlly, is a fairly minor fix

**Comment by remmeier** [comment]
new CrnkClient.setObjectMapper has been added, available from the latest repository (3.1.x)
