### ISSUE TITLE
Validation required on non primary key

### ISSUE THREAD

**Issue by JeyaNachiaban** [crnk-project/crnk-framework#370]
I have a table with id(Primary key),name,email and phoneno. I want to validate whether the phone no and emailid already exists. Can you please help me to do with crnk framework?

**Comment by remmeier** [comment]
can you provide more information? are you using crnk-jpa or a custom repository? you should be able to just make use of crnk-validation and provide a validator for emails. Or you can of course also do everything manually, maybe throw an exception and use a customer exception mapper.
