### ISSUE TITLE
Preventing fields from being updated on a PATCH request

### ISSUE THREAD

**Issue by duncanportelli** [crnk-project/crnk-framework#372]
I need to perform validation on specific fields, such that the user would be able to assign them a value on a POST request, yet would not be able to update their value in a PATCH request.  Since @JsonProperty provides limitation on READ and/or WRITE access only, I would not be able to perform such functionality using this annotation.  

A solution I was trying to implement was to retrieve the attributes specified by the user in the body of a PATCH request, so as to identify those fields that will be updated.  If I perform such a check from inside my repository class, I would not be able to identify the updated attributes since the resource would have already been merged.  

A potential solution I was investigating was extending the [`ResourcePatchController`](https://github.com/crnk-project/crnk-framework/blob/master/crnk-core/src/main/java/io/crnk/core/engine/internal/dispatcher/controller/ResourcePatchController.java) class so that I can get the list of updated attributes in my overridden `handleAsync(..)` method from the `requestDocument` parameter.  In order to implement such a solution, I would require to add my custom extended class as a controller instead of the default `ResourcePatchController`.  

Is there any way of how I can achieve such a behaviour?

**Comment by remmeier** [comment]
@JsonApiField.patchable seems what you are looking for? Or if you need more advanced logic, you can provide a custom ResourceFilter implementation.

**Comment by duncanportelli** [comment]
Yes @remmeier that is what I was looking for. Thanks!

However, I noticed that if a value for an attribute set as patchable=false is provided in the request body, crnk just ignores it and continues processing the request. Is there a way to throw an error and stop the PATCH request instead please?

**Comment by remmeier** [comment]
maybe it would be worthwhile to follow ResourceFilter that uses an enum with all three posiblities (do, ignore, error). But that would mean a new attributes in @JsonApiField (maybe updateable,...) and deprecate the current ones. Currently it only ignores the attribute and the ResourceFilter would have to be used.

**Comment by duncanportelli** [comment]
Hi @remmeier, thanks for your reply. I tried to make use of both the `ResourceFilter` and `ResourceModificationFilter`, and can confirm that the `ResourceFilter.filterField(..)` gets triggered correctly for each field in the patch request.

However, the method is triggered after the `findOne(..)` of the resource repository has been called. By any chance, do you know if there is any other way to trigger such validation before the `findOne(..)` is called please? I wish to achieve this in order to eliminate a database call (in `findOne(..)`) if my validation fails.

**Comment by duncanportelli** [comment]
Hi @remmeier,

Managed to achieve this by using the `DocumentFilter`. Thanks for all your help!

```
@Override
public Response filter(DocumentFilterContext context, DocumentFilterChain chain) {

	if (context.getMethod().equals(HttpMethod.PATCH.name())) {
		Set<String> modifiedAttributes = context.getRequestBody().getSingleData().get().getAttributes().keySet();

		List<ResourceField> forbiddenPatchFields =
			context.getQueryAdapter().getResourceInformation().getAttributeFields()
			.stream()
			.filter(field -> !field.getAccess().isPatchable() && modifiedAttributes.contains(field.getJsonName()))
				.collect(Collectors.toList());

		// Do logic
	}

	return super.filter(context, chain);
}
```
