### ISSUE TITLE
Empty attribute list if not fieldset is empty

### ISSUE THREAD

**Issue by yashprit** [crnk-project/crnk-framework#374]
We are using crnk with spring boot, our requirement is to send empty attributes if no fieldset is passed in url. First of all is it possible in crnk, if not can somebody guid me in that direction. My first approach was creating a class that extend Resource Repository add logic to check fieldset based on QuerySpec and all my resource will extend this new class instead of `ResourceRepository`.

I know this is very custom requirement, by default crank gives all attributes if no field-set is specified in  url

Thanks

**Comment by remmeier** [comment]
yes, with that default it also follows the JSON API specification. I guess if you really really want to have it like that, I would setup a custom DefaultQuerySpecUrlMapper and make use of the ID as default field set.

**Comment by yashprit** [comment]
Thanks @remmeier for update, yes we would like to have empty attribute object when no field set is passed in url. Is it possible to have that functionality inside crnk, like you mentioned something like `CustomDefaultQuerySpecUrlMapper`, if yes, I can send you pull request with your help.

**Comment by remmeier** [comment]
I think currently you can implement that custom url mapper just locally in the project. If more people request the feature, it can be moved back to crnk itself.

**Comment by yashprit** [comment]
@remmeier how to configure custom mapper as default mapper of all resource? Like PaggingSpec can we pass it to `@Import()` on Spring boot main Application class ?

**Comment by remmeier** [comment]
you can make use of a CrnkBootConfigurerer and set the url mapper. I think there is no service discovery yet for it, only a setter.

**Comment by yashprit** [comment]
Hi @remmeier regarding closed issues #362 are those changes released to production if yes which version

**Comment by remmeier** [comment]
http://www.crnk.io/releases/ => latest => http://www.crnk.io/releases/

all changes automatically go there. http://www.crnk.io/releases/stable/documentation/#_repository. No release to jcenter so far.

**Comment by yashprit** [comment]
Hi @remmeier 

Two resource Project and Task, TaskRepository has both PagedLinksInformation and PagedMetaInformation, while querying 

`http://localhost:8080/tasks?filter[project.id]=121&fields=project.id`
Produce result
``` json
{
    "data": [
        {
            "id": "1",
            "type": "tasks",
            "links": {
                "self": "http://localhost:8080/tasks/1"
            }
        }
    ],
    "links": {
        "first": null,
        "last": null,
        "next": null,
        "prev": null
    },
    "meta": {
        "totalResourceCount": null
    }
}
```

Where as `http://localhost:8080/projects/121/tasks` produce result 
``` json
{
    "data": [
        {
            "id": "1",
            "type": "tasks",
            "links": {
                "self": "http://localhost:8080/tasks/1"
            }
        }
    ]
}
```

During debugging, I found GetFromOppositeStrategy#findTargets()
```java
JsonApiResponse response = (JsonApiResponse)targetAdapter.findAll(this.context.createQueryAdapter(idQuerySpec, queryContext)).get();
```

`response` object contains Links Information but in subsequent code only entity information is what getting passed ignoring Link information.

Is this right behavior?

Thanks,
Yashprit

**Comment by remmeier** [comment]
not sure what the right behavior should be. So far meta/links information are not forwarded and used in case of relationship inclusions. But I can imagine use cases where you may want that. But that may rather be something done manually with some custom code rather then become the default?

**Comment by yashprit** [comment]
Is there anyway to achieve that using some custom code. 

Our application heavily around crnk framework and its feature along with Spring Boot. One of our use case is to find list of patch attributes while doing patch. I saw in one of documentation API to distinguish patched from un-patched fields is not yet (directly) available. Is there anyway to find our list of patched attribute in save method of repository class or any. 

thanks for your all help

**Comment by remmeier** [comment]
maybe the gitter forum is the better place or separate tickets, since there are different questions in this issue. 

you can collect the changes by implementing a ResourceModificationFilter. we make use of that as well to implement auditing.

**Comment by yashprit** [comment]
Sure, I am closing this issue. Thanks for all help
