### ISSUE TITLE
Can I register a Custom Serializer?

### ISSUE THREAD

**Issue by foxbaucia** [crnk-project/crnk-framework#388]
I'm trying to register a module to change the behavior of the base serialization of a DTO but I don't have any success. Is this possible?

I'm doing:
```
		ObjectMapper mapper = boot.getObjectMapper();
		mapper.disable(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS);
		mapper.disable(SerializationFeature.WRITE_DURATIONS_AS_TIMESTAMPS);
		SimpleModule module =
			new SimpleModule("MyDtoSerializer", new Version(1, 0, 0, null, null, null));
		module.addSerializer(MyDTO.class, new MyDTOSerializer());
		mapper.registerModule(module);
```
I know that the code is passing by these lines, the SerializationFeatures are working perfectly but seems that I can't register this module to redefine the base serialization.

Calling to MyDTO endpoint, when I add a breakpoint in MyDTOSerializer.serialize() it won't stop, and I get back the JSON with the base serialization.

**Comment by remmeier** [comment]
is the DTO an attribute or a resource itself? for the former it should work, for the later it does not since resources are mapped to `Document` and `Resource` object. Accordingly their serialization would have to be customized.

**Comment by foxbaucia** [comment]
Hello @remmeier, thanks for your quick answer. The DTO is the object to be returned by the service. Not an attribute. So I can't do this?

**Comment by remmeier** [comment]
what would you like to have changed? since the JSON API structure is specified like crnk is doing it. It is rather unusual to change it.

**Comment by foxbaucia** [comment]
Specifically, I want to not ignore null values in the JSON.
As @JsonIgnore is not working I thought to do it by defining a Serializer.

**Comment by remmeier** [comment]
aha, in this case that would be https://github.com/crnk-project/crnk-framework/issues/25. It is high on the wish list. Personally I still have a bit mixed feelings about it. I like the fact that people can discover the API. So if half of it gets hidden because it is empty, that is no longer possible.

**Comment by remmeier** [comment]
closing in favor of the mentioned issue  #25
