### ISSUE TITLE
Using different paging behaviors with included parameters gives errors

### ISSUE THREAD

**Issue by vicmosin** [crnk-project/crnk-framework#396]
`RepositoryAdapterUtils` fails with 

```
io.crnk.core.queryspec.pagingspec.OffsetLimitPagingSpec cannot be cast to io.crnk.core.queryspec.pagingspec.NumberSizePagingSpec
```

while 

```
if (pagingBehavior != null && pagingBehavior.isRequired(requestSpec.getQueryAdapter().getPagingSpec())) {
```

Reason is the following - `pagingBehavior` points to the current PagingBehavior object but `requestSpec.getQueryAdapter().getPagingSpec()` leads to the initial one which was provided with request. 

As a result, `pagingBehavior.isRequired(requestSpec.getQueryAdapter().getPagingSpec())` can't implicitely convert `PagingBehaviorA` to `isRequired(PagingBehaviorB)`

Simple solution could be adding additional check i.e. 

```
if (pagingBehavior != null && pagingBehavior.createEmptyPagingSpec().getClass().isInstance(requestSpec.getQueryAdapter().getPagingSpec()) && pagingBehavior.isRequired(requestSpec.getQueryAdapter().getPagingSpec())) {
```

to make sure both vars points to the same type.. But looks kinda odd..

@remmeier Any ideas?

**Comment by remmeier** [comment]
sorry, I missed this ticket😔. i guess QueryAdapter.getPagingSpec does not make much sense in the first place. it should take a ResoureInformation as parameter and get it from that QuerySpec (inclusions have separate QuerySpec).

**Comment by vicmosin** [comment]
@remmeier I am still kinda confused regarding this issue.. The main cause of the behaviour is `RepositoryAdapterUtils#l52` (if statement I mentioned on original issue) so it can be easily fixed with additional condition. But what I don't understand is whether it's a bug or wrong configuration from my side.

Issue is that `requestSpec.getQueryAdapter().getPagingSpec()` in check above is always instance of `OffsetLimitPagingSpec` because it is [set explicitely ](https://github.com/crnk-project/crnk-framework/blob/master/crnk-core/src/main/java/io/crnk/core/queryspec/QuerySpec.java#L56)at `QuerySpec` public constructor no matter which paging-spec is defined by resource itself. Is this correct?

**Comment by remmeier** [comment]
yes it is definately a bug.

**Comment by remmeier** [comment]
it is available on the latest repository, an official one next week again. Waiting for one other PR and potentially one, two things on my own.

**Comment by vicmosin** [comment]
@remmeier any updates regarding release?

**Comment by remmeier** [comment]
imminent, a few last discusions on
https://github.com/crnk-project/crnk-framework/pull/432

Am Mi., 26. Dez. 2018 um 18:39 Uhr schrieb Victor Mosin <
notifications@github.com>:
