### ISSUE TITLE
Support addSerializer to write filter parameters for links

### ISSUE THREAD

**Issue by jopsy** [crnk-project/crnk-framework#403]
DefaultQuerySpecUrlMapper.serializeValue could start making using of Jackson through the TypeParser. There it is already implemented to parse filter parameters, but not yet to write them.

**Comment by remmeier** [comment]
FYI: I committed support for bidirectional object <-> string mapping in TypeParser. So this ticket here can be addressed

**Comment by jopsy** [comment]
Thank you @remmeier
Closing this ticket

**Comment by remmeier** [comment]
also updated now the DefaultQuerySpecUrlMapper.serializeValue to make use of the new mapping functionality
