### ISSUE TITLE
Renamed attributes are not reflected validation result's error object

### ISSUE THREAD

**Issue by systemfreund** [crnk-project/crnk-framework#406]
Context: Spring MVC based project

```
class Resource {
    @NotBlank
    @JsonProperty("display-name")
    private String displayName;
}
```

When a client attempts to create this resource the server responds (422) with the following error object:

```
 {
  "errors" : [ {
    "status" : "422",
    "code" : "javax.validation.constraints.NotBlank",
    "detail" : "must not be blank",
    "source" : {
      "pointer" : "/data/attributes/displayName"
    },
   ...
  } ]
}
```

As you can see the JSON-pointer contains pojo's field-name instead of the "public" name

**Comment by remmeier** [comment]
yes, needs to be supported in ConstraintViolationExceptionMapper$ResourceRef.visitProperty(...) and the other way around in ConstraintViolationImpl.toPath. For this purpose the ResourceRegistry holds the ResourceInformation, which hold then information about the renaming.

If it is also supposed to be supported for nested property, then https://github.com/crnk-project/crnk-framework/issues/399 needs to be addressed as well.

A PR would be  welcomed if there is time.
