### ISSUE TITLE
findOne is not returning 404 when entity does not exist

### ISSUE THREAD

**Issue by remmeier** [crnk-project/crnk-framework#41]
from @phuo1032

am I suppose to throw the NOT_FOUND exception manually?

**Comment by mohlek** [comment]
In my abstract repository I am throwing an exception if the result is null.
But I think this should be the default behavior. Nothing I have to do on my
own.

Remo <notifications@github.com> schrieb am So., 25. Juni 2017, 19:17:

**Comment by mohlek** [comment]
can be closed
