### ISSUE TITLE
Issue in documentation

### ISSUE THREAD

**Issue by Kipyshaz** [crnk-project/crnk-framework#411]
Reading documentation and I noticed that there is an issue related with text in section: https://github.com/crnk-project/crnk-framework/blob/master/crnk-documentation/src/docs/asciidoc/repositories.adoc#bulkrelationshiprepositoryv2.
Sentence:
Note that in contrast to RelationshipRepositoryV2 and **_RelationshipRepositoryV2_** that are symmetric and applicable to Crnk servers and client, BulkRelationshipRepositoryV2 is applicable on the server-side only. 

Maybe word marked as italic bold text should be **ForwardingRelationshipRepository**?

**Comment by remmeier** [comment]
I think it should be ResourceRepositoryV2. Fixed. Thx!
