### ISSUE TITLE
add support for facets

### ISSUE THREAD

**Issue by remmeier** [crnk-project/crnk-framework#413]
it is quite typical for UIs/tables to list the set of possible filter values, potentially combined with a count that displays the number results whe  applying a given filter/facet. amazon is a prominent example of such a facetted search. 

goal of this ticket would be to implement a generic repository to make such information accessible. a facet is represented by a resource and holds the type, attribute, set of values, set of counts, a name and the necessary filter.

the facets can be applied to different repositories. initially, two kinds are supported: in-memory and jpa, with the later being more efficient using the SQL group by clause. elastic search would be a possible third candidate

**Comment by yashprit** [comment]
@remmeier are you talking about resource-repository here, or data-repository? What will be url to access these facets. Is this part of resource or different payload. Can you post sample request (payload + URI) and response to get more insight about requirement.

**Comment by remmeier** [comment]
it will be an entirely separate resource with the fields mentioned above. the set of facets is then selected/computed based on the passed filter parameter. for example restricting/filtering by one facet will also lead to update to related facet resources.without any filters you get all counts for all facets for every resource type.

can make an example early next week.

**Comment by remmeier** [comment]
an initial version is now available
