### ISSUE TITLE
Using `@JsonApiField(patchable = false)` on a relationship field has no effect

### ISSUE THREAD

**Issue by systemfreund** [crnk-project/crnk-framework#428]
When a relationship field is annotated like above I would expect that a PATCH request in which the relationship is set, crnk would ignore it due to the annotation. But it seems that the annotation is ignored for relationship fields.

Now I am not sure if this is a bug or intended behaviour, also because the `JsonApiField`'s javadoc specifically mentions "attributes" and not "relationships".

**Comment by remmeier** [comment]
done
