### ISSUE TITLE
Validation not done on fields inside a nested object

### ISSUE THREAD

**Issue by duncanportelli** [crnk-project/crnk-framework#429]
I am currently performing validation on the attributes in my resource by annotating them accordingly. However, I noticed that validation is being done on first level attributes but not on attributes found in a nested object.

As an example, let's say I have the following classes representing a Person object:

```
@JsonApiResource(type = "persons")
public class Person {
    
    @NotBlank
    private String name;

    @NotBlank
    private String surname;

    @NotNull
    private Address address;
}

public class Address {

    @NotBlank
    private String addr1;

    private String addr2;
}
```

Validation is successfully done on `name` and `surname`. However, the validation on `addr1` is not being done. Is there any way I can trigger the validation on `addr1` attribute as well?

**Comment by remmeier** [comment]
does @Valid on address help? https://stackoverflow.com/questions/5142065/jsr-303-valid-annotation-nested-object-not-working. Or are you then running into further issues?

**Comment by duncanportelli** [comment]
Thanks @remmeier. I was annotating the whole Person object with @Valid and that didn't work. However, annotating the Address object with @Valid worked :) Cheers
