### ISSUE TITLE
MetaLookup of generic members

### ISSUE THREAD

**Issue by lorenzleutgeb** [crnk-project/crnk-framework#430]
Hi!

Consider the following case of an entity that inherits from a superclass with generics:

```java
@MappedSuperclass
class Superclass<T> {
  @Column
  T foo;
  ...
  // Imagine some getters, setters and an empty ctor.
}

@Entity
class MyEntity extends Superclass<String> {
  ...
  // Imagine some @Id, other getters, setters and an empty ctor.
}
```

The discovery of `Superclass#foo` will not work: It will produce an `IllegalStateException` thrown by `io.crnk.core.engine.internal.utils.ClassUtils#getRawType` https://github.com/crnk-project/crnk-framework/blob/aa6497460633e1c0bcc07374b7d98b2d74aa0a97/crnk-core/src/main/java/io/crnk/core/engine/internal/utils/ClassUtils.java#L372-L380 since the type it receives is a [`sun.reflect.generics.reflectiveObjects.TypeVariableImpl`](https://hg.openjdk.java.net/jdk-updates/jdk11u/file/16d5ec7dbbb4/src/java.base/share/classes/sun/reflect/generics/reflectiveObjects/TypeVariableImpl.java).

### Case 1: This behaviour is intended and you do not want to change the situation anytime soon:

crnk's default implementation of `MetaProvider` does not handle this case on purpose. If so, then my request is to add the case of type variables to `getRawType` and throw a more specific exception with a message saying that generics are not supported. In addition, the documentation should mentation this.

### Case 2: You want to allow this case:

Otherwise, you would have to improve your logic and do some simple type inference: When you handle `Superclass#foo` the context of `MyEntity` and its concretization for `T` is of relevance. You will never be able to get the actual type of `foo` by looking at its decalaration locally. However it looks like this is exactly what is happening in your current implementation: In this case the `TypeVariableImpl` would just carry its name `"T"` and its bounds (which are none in my example).
Also, I am wondering why the superclass is even inspected so closely, since it is not an actual entity but only the superclass. My guess is that you get to the declaration in the superclass since it is also a declaration in the entity by inheritance. But I did not investigate so far into your code.

**Comment by remmeier** [comment]
definately case 2 but just not implemented. There might be similar issues in the ResourceRegistry. Have to take a closer look. Potentially `net.jodah:typetools:0.5.0` used by crnk-core can also help a bit. Recently we started a bit to move away from PropertyUtils and rather use the BeanInformation. So potentially by integrating typetools with BeanInformation the problem could be solved in the entire code base (meta + resource registry) and in a more or less "simple" fashion. What we also may have to think about is not just keeping the declared MetaAttribute in a MetaDataObject, but all of them with properly resolved types. Not quite sure yet what kind of consequences this will entail tough. ResourceRegistry is already implemented like this.

**Comment by lorenzleutgeb** [comment]
Indeed, in my first attempt #432 I reimplemented some functionality of the dependency you mentioned. I have to say that all the type discovery code is not simple, but I will try to see how one might use `BeanInformation` powered by `net.jodah:typetools`.

I do not understand the part where you are talking about `MetaAttribute`, `MetaDataObject` and `ResourceRegistry`. It seems that I just do not know your codebase well enough. Maybe you could explain that a bit more in depth?

**Comment by remmeier** [comment]
`MetaDataObject` holds one or more `MetaAttribute`. There is a distinction between declared and all attributes. The former are the ones of the type itself, the later all including the ones inherited from subertype (just as in Java reflections). Current in `MetaDataObject` all attributes are returned by collecting the declarted attributes of the current and all super type. In this case here, resolving generic types of attributes in a subtype, this will not work. You rather need all attribute per type solved based on the type constraints of this type.

**Comment by lorenzleutgeb** [comment]
OK. Could you have a look at my changes and comment on whether my direction is correct? Significantly less test are failing now, compared to yesterday.

**Comment by lorenzleutgeb** [comment]
One limitation of `net.jodah:typetools`'s `TypeResolver` is that it does only allow resolution of raw types, not parameterized types. So if I know have a `List<T>` and some instantiation for `T`, say `Integer`, the resolver will just give me `List`, not `List<Integer>`.

**Comment by remmeier** [comment]
done
