### ISSUE TITLE
Include stoped to work after upgrade to recent version

### ISSUE THREAD

**Issue by vicmosin** [crnk-project/crnk-framework#444]
Some of the private forks -> 2.10.20181129142450
Nothing changed in code. Do I miss something @remmeier ?

Thanks in advance

**Comment by remmeier** [comment]
latest -> 2.11.x

http://www.crnk.io/releases/latest/

**Comment by vicmosin** [comment]
It's not yet available so I wanted to go first with official release

**Comment by remmeier** [comment]
yes, but available from the private repo

**Comment by vicmosin** [comment]
Alright, I guess I found the bug. Imagine the following case:

```
public class Resource {
 ... 
   @JsonProperty("any-resource")
   @JsonApiRelation(serialize = SerializeType.ONLY_ID, lookUp = LookupIncludeBehavior.AUTOMATICALLY_WHEN_NULL)
    private AnyResource anyResource;
}
```
and request `curl http://some/resource/x?include=any-form`.

Issue is that `IncludeLookupUtil.isInclusionRequested` gets `anyResource` as part of first parameter and `any-resource` as second.. as result, it can't actually compare 2 different namings..

Will try to provide fix shortly

**Comment by remmeier** [comment]
QueryAdapter should hold the Java naming. And fieldPath holding both names. The getJsonName usage seems odd in this class.

**Comment by vicmosin** [comment]
> QueryAdapter should hold the Java naming
correct
> fieldPath holding both names
this looks wrong

**Comment by remmeier** [comment]
DefaultQuerySpecUrlMapper is on place? or are there deprecation warnings on
startup?

Am Mo., 17. Dez. 2018, 14:12 hat Victor Mosin <notifications@github.com>
geschrieben:

**Comment by vicmosin** [comment]
What exactly do you mean? You found the reason already..  `getJsonName` should be replaced with `getUnderlyingName`
