### ISSUE TITLE
Prometheus support

### ISSUE THREAD

**Issue by vicmosin** [crnk-project/crnk-framework#451]
i.e. metrics. Any work in that direction?

**Comment by remmeier** [comment]
not so far, but would be interesting to have. Through a module and various filters quite easy to achieve. I think support for micrometer would be interesting (as it is also the default stack of spring). It would allow to target not only Prometheus, but also ElasticSearch and others in a generic way.

**Comment by vicmosin** [comment]
I'll try to find some time since it's in our backlog but can provide only spring support. 
Which module name do you prefer?

**Comment by vicmosin** [comment]
@remmeier any feedback to this? I am kinda ready to push but don't want to do double work :)

**Comment by vicmosin** [comment]
Alright, as I said I have no enough time to go deep into crnk core, but spring integration I've done.

Here is the deal: in order to generate proper metrics/prometheus data [WebMvcMetricsFilter](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/metrics/web/servlet/WebMvcMetricsFilter.java) uses by default instance of [DefaultWebMvcTagsProvider](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/metrics/web/servlet/DefaultWebMvcTagsProvider.java) to build appropriate tags (i.e. actual info goes to prometheus: uri, request type etc). Now, internal logics of uri retrieval is tightly coupled to spring impl, meaning it tries to get the uri from request attribute's `org.springframework.web.servlet.HandlerMapping.bestMatchingPattern` value. The result of that - all the requests to crnk recources are being recorded but with default values and look like:
```
http_server_requests_seconds_count{exception="None",method="GET",status="200",uri="root",} 3001.0
http_server_requests_seconds_sum{exception="None",method="GET",status="200",uri="root",} 2.342699523
http_server_requests_seconds_max{exception="None",method="GET",status="200",uri="root",} 6.77258E-4
```

My idea is to have some custom composite impl of [WebMvcTagsProvider](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/metrics/web/servlet/WebMvcTagsProvider.java) which uses ResourceRegistry in order to determine whether request is crnk-based (i.e. crnk dispatcher should handle it) and generate appropriate tags or use DefaultWebMvcTagsProvider as fallback case (i.e. for all non crnk requests)
