### ISSUE TITLE
Weird failure by using multiple pagination

### ISSUE THREAD

**Issue by vicmosin** [crnk-project/crnk-framework#453]
I've found one interesting case which isn't covered by tests and caused failure with:

`java.lang.ClassCastException: io.crnk.core.queryspec.pagingspec.OffsetLimitPagingSpec cannot be cast to io.crnk.core.queryspec.pagingspec.NumberSizePagingSpec`

ResourceA with NumberSizePagingSpec and resourceB with default one (i.e. OffsetLimitPagingSpec).
* As soon as one makes `resourceB?include[resourceA]=...` works fine
* As soon as it makes opposite request i.e. `resourceA?include[resourceB]=...` request fails with error above.

It actually happens because `DefaultQuerySpecUrlMapper` [trying to serialize](https://github.com/crnk-project/crnk-framework/blob/master/crnk-core/src/main/java/io/crnk/core/queryspec/mapper/DefaultQuerySpecUrlMapper.java#L294) the `PagingBehavior` of resourceA with `QuerySpec` holding `PagingBehavior` of resourceB

**Comment by vicmosin** [comment]
Ok, I guess I can define the issue better now. 

QuerySpec by default holds an instance of `OffsetLimit` pagination and as soon as one tries to read any resource which has PagingSpec other than that (for example, `NumberSize`) and request has no info about paging, the default one is used. That's what actually causing `ClassCastException`:
```
pagingBehavior.serialize(querySpec.getPaging(), resourceType)
```
where `pagingBehavior` is `NumberSize` (as defined in resource)
and `querySpec.getPaging()` is `OffsetLimit` (as no other pagination was provided via request and default is used).

@remmeier any ideas how should crnk handle such case?

**Comment by remmeier** [comment]
PagingBehavior provides the possiblity to create an empty paging spec. Where does it still happen that a wrong paging spec is in use? For today, tomorrow maybe that could be changed/fixed. Mid-term it would maybe be reasonable to switch that to having a null pagingspec by default. I have some changes on the way that would also warrant doing a 3.x release after the 2.11.
