### ISSUE TITLE
Minified/entire resources via related link

### ISSUE THREAD

**Issue by vicmosin** [crnk-project/crnk-framework#456]
http://www.crnk.io/releases/v2.9/ (see Relationships loading handled according to JSON API specification part) introduced change which removed entire resource from response in case of self link is used. Now, if I follow any paging link from response, I get no entire resource as well. That's ok.

If I follow `related` link, I get response with entire resources, according to the docs, good so far. But the issue is that in this case pagination links are `self` links which means even if I follow the next link from `related` link response I still get minified resource (and I would expect entire one since I used `related` link originally). 

Does it make sense? Otherwise, if client has to provide `fields` (in order to include attributes explicitely) it would be breaking change and I can't easy upgrade to latest version

**Comment by remmeier** [comment]
yes, that is not correct. if one follows the related links with the full-resources, you should also stay on the full resources when visiting subsequent paging links. Seems that just that paging link computation does not yet honor the difference between self/related. Did not think about that area when implementing it :-(

**Comment by vicmosin** [comment]
@remmeier It looks like there is no any sign of self/related link currently in the code.. 

Handling of entire/minified response is kinda spread across the engine, i.e. definition of minified resource is done via including `id` field only and the determination logic is based on the fact that there is any relation requested (without any difference if it was self link or related), but link generation is done at other layer where we can't really determine which link it should be (self or related).

I was thinking about using `QueryContext` as a holder for that info. We could add `bool self` or even reuse attributes map (not sure why it's used now). And since this object is part of QueryAdapter this information will be available at almost every layer of the engine..

Or do you have another ideas? This one is kinda critical for me, since it introduced breaking changes..

**Comment by remmeier** [comment]
QueryContext sounds good to me. And the JsonApiUrlBuilder can then make use of it. That may suffice?

**Comment by vicmosin** [comment]
I changed a bit initial idea and moved that info to QuerySpecAdapter as QueryContext looked somehow a bit wrong to me, while context still holding the request path
