### ISSUE TITLE
meta data response not consistent with findAll and findOne

### ISSUE THREAD

**Issue by shadab08** [crnk-project/crnk-framework#461]
**Crnk Version:** 2.11.20190113153635

The API response containing meta information is not consistent in the findAll and findOne response.

With findAll where I am attaching meta information to the list, the meta field is coming as sibling of data which is correct as per JSON API specs. See below sample response.

`{
  "data" : {
    "id" : "12345",
    "type" : "res_type",
    "attributes" : {
    }
  },
  "meta" : {
	"totalResourceCount" : 1
  }
}`

But when I am attaching meta information to a resource using annotation @JsonApiMetaInformation, the meta information is coming as child of data field. See below sample

`{
  "data" : {
    "id" : "12345",
    "type" : "res_type",
    "attributes" : {
    },
    "meta" : {
      "totalResourceCount" : 1
    }
  }
}`

I am referring to the code sample provided in cheatsheet [here](http://www.crnk.io/releases/latest/documentation/cheatsheet.html#_information).

Is this a bug or an expected behavior or am I missing something. 
Please help!

Thanks.

**Comment by remmeier** [comment]
I think it is consistent but not entirely understandable at first sight.

There are many different meta information: root of the response, individual resources or relationships

@JsonApiMetaInformation is for resources, as such all those meta information are contained within the resource (data section)

MetaRepositoryV2 can be implemented to return meta information in the root. A shortcut is by setting  the meta information in ResourceList. That part is maybe not entirely self-explaining. To some degree I would like it to be symmetric, meaning findOne and fineAll can both somehow set the root resource. But not sure how the API would look like and whether it is worth the effort (like something similar to ResourceList, but just for one resource).

**Comment by remmeier** [comment]
=> feel free to suggest doc updates

**Comment by shadab08** [comment]
@remmeier Thanks for the clarification. I think this make sense to me now.

I have already implemented MetaRepositoryV2 for the ResourceList and @JsonApiMetaInformation  is working for findOne scenerio. I think we can keep using it this way as we now know what to expect in the APIs response.

Thanks again for your response :)
