### ISSUE TITLE
Unable to create a resource using a DTO

### ISSUE THREAD

**Issue by JochenReinhardt** [crnk-project/crnk-framework#462]
When trying to create a resource (POST without ID), I get an error: 
```
java.lang.IllegalStateException: id not available for entity ModernDTO(id=null, value=Test New)
	at io.crnk.core.engine.internal.utils.PreconditionUtil.fail(PreconditionUtil.java:50) ~[crnk-core-2.11.20190113153635.jar:na]
	at io.crnk.core.engine.internal.utils.PreconditionUtil.verify(PreconditionUtil.java:131) ~[crnk-core-2.11.20190113153635.jar:na]
	at io.crnk.jpa.JpaEntityRepositoryBase.saveInternal(JpaEntityRepositoryBase.java:188) ~[crnk-jpa-2.11.20190113153635.jar:na]
	at io.crnk.jpa.JpaEntityRepositoryBase.create(JpaEntityRepositoryBase.java:162) ~[crnk-jpa-2.11.20190113153635.jar:na]
```

I have created a Spring Boot demo application for the issue: https://github.com/JochenReinhardt/crnk-jpa-dto-demo

The issue seems to be with the following lines of code in `JpaEntityRepositoryBase.saveInternal`:
```java
        // id may differ from primary key
        ResourceField idField = getIdField();
        I id = (I) idField.getAccessor().getValue(resource);
        PreconditionUtil.verify(id != null, "id not available for entity %s", resource);
 ```

`resource` is the DTO passed into the `saveInternal` method. The entity is created and an ID is generated automatically by Hibernate. But the incoming `resource` is not updated. This is why the precondition fails in this case.

Is it possible to update the DTO with the ID from the entity in such a case?

After an entity is created or updated, don't we need a call to `em.flush()` to make sure the finder finds the updated entity?

**Comment by remmeier** [comment]
kind of interesting, yes a flush seems necessary to resolve the issue. There is a testSequencePrimaryKey within JpaEntityRepositoryTestBase that covers this particular use case and I have seen it working in other palces. But also noticed it once not working. So something seems of and probably better to add that flush. Altough for bulk updates it might not be desired, so it should be possible to disable it again or maybe even perform the flush only for generated primary keys.

**Comment by JochenReinhardt** [comment]
Most important to me is, that the create works using a DTO.
In my case, DTO and entity use the same field names and the JSON-API ID is the same as the Entity ID. But the DTO does not have an ID in case of the create request. The autogenerated ID should be assigned to the DTO, too. This should make the precondition check and the subsequent find call work correctly.

Are you going to fix this issue?
Can I help?

I'm not really sure about the flush. It could also be that the persistence provider automatically performs the flush when it recognizes that the entity is queried usind JPA.

**Comment by remmeier** [comment]
should oyu have time you can create a PR to add this flush (e.g. with the possiblity to disable it with a property like JpaRepositoryConfig.flushEntities).

**Comment by JochenReinhardt** [comment]
OK. I hope I can open the pull request in the next couple of days.

**Comment by JochenReinhardt** [comment]
Pull request is open.
The entity's ID is present right after the call to persist. No need for a flush.
The finder creats a query for the entity. At least for JPA/Hibernate this should trigger a flush to the database before the query is actually executed.
When the query is executed, the updated value is found.
