### ISSUE TITLE
Support OpenTracing

### ISSUE THREAD

**Issue by remmeier** [crnk-project/crnk-framework#477]
in general tracing is an issue for the underlying HTTP layer to trace all kinds of calls, not just HTTP. But it is worthwhile to add dedicated support. Most notably a reasonable span name should be set.

**Comment by adriancole** [comment]
if this is not just adding opentracing, but moving off zipkin, then probably it is no longer appropriate to tag this repo zipkin

**Comment by adriancole** [comment]
I think some of your assumptions are a bit off. Brave logs by default to
console for exactly reasons you mention. The old api though isn't helpful.
A replacement has been available for years. OT isn't a standard either
https://opentracing.io/docs/overview/what-is-tracing/#what-is-opentracing

anyway this is your project, just trying to help confuse folks less. OT
causes enough confusion as it is

**Comment by remmeier** [comment]
yes, "standard" was the wrong word here. The standard part comes more from things like the W3C Trace Context specification. In general we work with many different companies and see quite a bit of momentum in the area of OpenTracing (and CNCF in general). Each of those companies has their own monitoring infrastructure in place. So writing software agnostic to these helps a lot, the place where OpenTracing shines. And in that regard looking forward to the work of W3C. OpenTracing is also not the only thing in town, but currently seems to enjoy healthy traction/publicity.

**Comment by adriancole** [comment]
it does enjoy a lot of CNCF and otherwise sponsored marketing. agreed

**Comment by remmeier** [comment]
I guess in general the entire tracing topic got quite a boost from the kubernetes/cloud native community, which is great to see. Currently I hope that there is a bit more collaboration between OpenTracing, OpenMetrics, OpenCensus, because all of them have interesting pieces but also duplication.
