### ISSUE TITLE
Using MethodNotAllowedException in the ReadOnly repositories

### ISSUE THREAD

**Issue by datagitlies** [crnk-project/crnk-framework#496]
**Problem:** The read only repositories `ReadOnlyResourceRepositoryBase` and `ReadOnlyRelationshipRepositoryBase` currently throw an `UnsupportedOperationException` for the non-read operations. This results in clients receiving an HTTP 500 Internal Server Error status when instead they should receive an HTTP 405 Method Not Allowed status.

**Solution:** Throw `MethodNotAllowedException` from the non-read operations.

I was about to start working on a pull request to change this but I figured I should ask about it via an issue first. If this is an easy "win" I'll gladly contribute the change via pull request.

**Comment by remmeier** [comment]
sounds good to me. Yes a ticket in advance is always good to discuss first. Plan would be to release the next version as 3.0.x-beta in the next few days. In that sense it is a very minor breaking change as nobody should build upon the current behavior (500 & UnsupportedOperationException ). PR would be very welcomed.  The change can be documented in the documentation => release => latest notes.
