### ISSUE TITLE
include related resources if the relationship field contains data

### ISSUE THREAD

**Issue by aawaken** [crnk-project/crnk-framework#521]
Hello,
At the moment, crnk serializes a related resources into "include" clause only if explicitly requested in url with LAZY strategy or with EAGER strategy. Our requirement is however to include dependencies if the repository itself decides that, not just ever or never.

Is it possible that crnk includes a related resource depending just on that the relationship field contains a resource?

Thanks

**Comment by remmeier** [comment]
i think setting it to EAGER and using the IncludeLookupBehavior to NEVER is what you are looking for. it gives full control to a repository.

**Comment by aawaken** [comment]
Thanks a lot, I'll try it out!
