### ISSUE TITLE
More flexibility for Operations-Module error handling

### ISSUE THREAD

**Issue by JochenReinhardt** [crnk-project/crnk-framework#525]
We need more flexibility when handling errors in the Operations module.

The current implementation stops processing as soon as the first error (HTTP status >= 400) occurs and skips all remaining requests with HTTP status 412 Precondition Failed.

We would need some way to ignore errors and continue processing anyways. I am going to open a PR for this shortly.

**Comment by remmeier** [comment]
would be great, thx!

**Comment by JochenReinhardt** [comment]
PR #530 opened. Sorry for the delay...

**Comment by remmeier** [comment]
merged awhile ago, so closing the ticket
