### ISSUE TITLE
Setup crnk to use with objectify

### ISSUE THREAD

**Issue by DeafLight** [crnk-project/crnk-framework#528]
I'm trying to build an API (using the [JSON:API](https://jsonapi.org/) spec) on top of a Google Datastore which currently uses [Objectify](https://github.com/objectify/objectify) to access the data.

crnk seems promising, but it seems to be tight coupled with JPA, which is explicitly [not recommended](https://cloud.google.com/appengine/docs/standard/java/datastore/jpa/overview) to be used with this specific datastore.

Is there a way to achieve something like that ? An existing third party crnk/objectify module maybe ? Another JSON:API framework ? Or are we stuck with JPA ?
I'm aware that the difference that exists between relational storage and datastores would most certainly imply some manual mapping to declare the relationships between objects, but any other insights could help.

Thanks :)

**Comment by corrspt** [comment]
I think you can use whatever you want with Crnk, and aren't tied to JPA.
 
You need to implement the repositories (`ResourceRepositoryV2`) and annotate the resources and have a way to let crnk process the request (servlet, spring, etc... - the are several modules for that). 

Even if you can't find a specific module for your situation, you can always integrate manually (I've done that to use the Play Framework with Crnk).

It probably is more `convenient` to use the pre-made modules as that is code you don't have to write to start, but that shouldn't be a blocker for you/your team.

**Comment by remmeier** [comment]
totally agree, jpa is one small part of it.

you may also look at the generator sources. we already make use of it for typescript and documenation, might be of help in your case as well. Or the meta model as available as Rest API to build up bindings dynamically. overall there is a large degree of flexibility through additional modules if something does not fit.

**Comment by DeafLight** [comment]
Thanks for the insights.

Starting from the [minimal example](https://github.com/crnk-project/crnk-framework/tree/master/crnk-integration-examples/spring-boot-minimal-example), it seems like we can fetch the data by calling Objectify directly from the repositories, that's nice :)

Does that mean that the way to go would be to translate the querySpec properties into Objectify commands in order to build the query os needed ? Or is there another approach ?
