### ISSUE TITLE
Jackson JsonAnySetter support to for dynamic fields using crnk-client

### ISSUE THREAD

**Issue by magg** [crnk-project/crnk-framework#536]
Hello 

According to the documentation JsonAnySetter and JsonAnyGetter are supported but my tests show otherwise

I'm using ` <crnk.version>3.0.20190606072637-BETA</crnk.version>`

I'm trying to create an object and the attributes fields are not included on creation. I'm using to crnk-client to create a object on a remote server. Funny thing is, the json it's populated correctly when it comes back from the server. But it's not populated correctly on the client before sending it to the server

```
@JsonApiResource
@JsonInclude(JsonInclude.Include.NON_DEFAULT)
public class Customer {

    @JsonApiId
    protected Long id;
    private String name;


    @JsonIgnore
    protected Map<String, Object> customFields = new LinkedHashMap<>();

    @JsonAnyGetter
    public Map<String,Object> any() {
        return customFields;
    }

    @JsonAnySetter
    public void set(String name, Object value) {
        customFields.put(name, value);
    }
```

it generates the following: (all fields in the customFields map are missing from the attributes json block)

```
"data” : {
   “type” : “customer”,
   “attributes” : {
     “name” : “Amy”
   }
 }
```

I'm instantiating the class like so Customer c = new Customer(); and setting c.set("email", "lol@outlook.com"); c.setName("Amy")

Any help is appreciated

thanks!
- Miguel

**Comment by remmeier** [comment]
looks like it is not supported as of yet in the client. Historically the @JsonApiSetter has been much older than crnk-client and not so much used. So it seems that it slipped.

There is a `ResourceInformation.getAnyFieldAccessor` that needs to be adopted in `ResourceMapper.setAttributes`. Then it shoulds be fine.

**Comment by magg** [comment]
hi @remmeier is it an easy change then? do you think it can be merged soon?

**Comment by remmeier** [comment]
yes rather small I think. If you have time you can have a look. Otherwise I try to make time.

**Comment by magg** [comment]
Hello @remmeier can you please review PR https://github.com/crnk-project/crnk-framework/pull/537

I tested and it it generates the json i need, I need this to be merged before Monday hopefully

**Comment by magg** [comment]
closing issue as my PR was already merged

thanks!
