### ISSUE TITLE
use crnk to create response which can be submitted via other means (i.e. web socket)

### ISSUE THREAD

**Issue by st-h** [crnk-project/crnk-framework#540]
Our vertx application both makes use of a rest interface as well as pushes data out to clients asynchronously via a web socket. We would like to use the same code which translates the JsonApiResources into JsonApi strings for the web socket as we do for the rest interface.

Is there a way to just pass all the needed java objects to crnk and have it generate an appropriate json response which we then can pass to the websocket?

**Comment by remmeier** [comment]
yes, absolutetly since it already integrates into various technology stacks. Examples for this are for example `CrnkFilter` or `InMemoryHttpAdapter`. They make use of the requestDispatcher and provide a request/response object.

**Comment by st-h** [comment]
@remmeier Thank you. I will have a look
