### ISSUE TITLE
Crnk-client more support for relations

### ISSUE THREAD

**Issue by ryan13mt** [crnk-project/crnk-framework#547]
I have this piece of code 

``
RelationshipRepositoryV2<Resource, String, Resource, String> repository =          client.getRepositoryForPath("parent","child");

repository.findManyTargets("parentId", "child", null);
``

This will call-> localhost:8080/parent/parentId/relationships/child
and only provide the relationship with the child id so to get all the children i will have to make another call with the id's.

I cannot find a way that will call-> localhost:8080/parent/parentId/child 
and provide with a list of children

**Comment by remmeier** [comment]
I think that is an error. It should call it without "relationship". Ther error likely has historic reasons. Till a few releases there was to distinction between with/without "relationship", so it worked either way. And 99% of users will make use of the other non-generic methods, so this never got noticed. We have to check JsonApiUrlBuilder.buildUrlInternal(...) to not include the "relationship" by having selflink equals 0. you are currently using 3.0 already?

**Comment by ryan13mt** [comment]
No we are on 2.6 currently. Is there a way around this issue or should we wait for a fix and for now just call the child resource with the id's?

**Comment by ryan13mt** [comment]
Even if i add the "include" in the Query Spec, the included resources will be removed when the json body is converted into a Resource since that will include only the "data" in the json response and discard the "included". So that is another way it could have worked without having to call each id separately but unfortunately it doesn't.

**Comment by ryan13mt** [comment]
Upgrading to 3.0 solved the issue

**Comment by remmeier** [comment]
ah ok perfect
