### ISSUE TITLE
PropertyException: Cannot find an getter for java.lang.String.id

### ISSUE THREAD

**Issue by nayrban** [crnk-project/crnk-framework#552]
I am not sure if I am doing something wrong here, but what happens if that list has more than one item?

I am facing some errors here 

I am using InMemory since I am using jooq with a custom implementation

https://github.com/crnk-project/crnk-framework/blob/92f0e02d9759e7aa75610571327def979502f7f5/crnk-core/src/main/java/io/crnk/core/engine/internal/utils/PropertyUtils.java#L89

One to many relationship
` 
//Model 1
  @JsonApiRelation(
    lookUp = LookupIncludeBehavior.AUTOMATICALLY_WHEN_NULL, opposite = "campusId",
    repositoryBehavior = RelationshipRepositoryBehavior.FORWARD_OPPOSITE)
  val teachers: util.List[TeacherModel] = ....

//Model 2
  @JsonApiRelationId()
  var _campusId: String = teacherRecord.getCampusid

`

**Comment by remmeier** [comment]
What is the complete stack trace?

Some other nodes:
- With crnk 3.0 you can simplify the teacher side with `@JsonApiRelation(mappedBy="campusId"). 
- JOOQ in general would be intresting to support. In that case then without in-memoy sorting/filtering, but by translating the queries to sql just as crnk-jpa does. probably many things could be reused for this.
- I would consider leaving the resources empty of any logic, just plain getter/setter. Than you can reuse it on the client side, e.g. for testing where there is no teacherRecord and other things available. If "teachers" is initialized, it would also not need the forwarding behavior and inclusion behavior. But probably better to leave it null and let crnk fill it up (assuming the filtering is implemented).

**Comment by nayrban** [comment]
thanks @remmeier ,
Yeah, yesterday night  I updated to 3.0.X and added this to Model 2

`  @JsonApiRelation
  var campus:CampusModel = null
`
I set it null because with Scala I need to define the variable, but it works fairly well.

Also will be great to have support for Jooq . :D
I am really happy because of the Scala and Java interoperability.

Thanks again for your quick response.

**Comment by remmeier** [comment]
should you have some first pieces for a jooq repository, feel free to dump it here in a ticket or  PR. Could be a first setup for an official jooq repository. I think could be of interesting to various people. Together with the async postgresql drivers and similar things could also give quite some benefits in terms of performance.
