### ISSUE TITLE
JsonProperty not found on nested relation

### ISSUE THREAD

**Issue by franekozulic** [crnk-project/crnk-framework#595]
I'm using a JsonProperty on a relation attribute. 
The child resources is set as nested. When i try to access to child resource the url can not be created because it compares the name with the json-name. 

The problem is in the io.crnk.core.engine.internal.registry.ResourceRegistryImpl class the getResourceUrl method (line 149) the childrenField is always nulll.

The childrenField can not be found because it passes the name (parentField.getOppositeName()) to the io.crnk.core.engine.information.resource.ResourceInformation class findRelationshipFieldByField method and there it compares the javaname with the jsonname in this case they are not the same.

Example

Master Resource with JsonProperty
....
  @JsonProperty(value = "child-of-the-parent")
  private List<Child> child;

with the parentField.getOppositeName() it has the "child" and the jsonName is "child-of-the-parent" so it can not find it.

As a workaround I created a new method in the ResourceInformation where the ResourceField can be passed. Then try to find with the jsonName and if not found try to find with the underlayingName.  Maybe it can directly use the fieldByUnderlyingName.get("") method.

io.crnk.core.engine.internal.registry.ResourceRegistryImpl
    @Override
    public String getResourceUrl(QueryContext queryContext, ResourceInformation 
    resourceInformation, Object id) {
     if (resourceInformation.isNested()) {
     ResourceField parentField = resourceInformation.getParentField();
     RegistryEntry parentEntry = getEntry(parentField.getOppositeResourceType());
     ResourceInformation parentInformation = parentEntry.getResourceInformation();
     ResourceField childrenField = parentInformation.findRelationshipFieldByField(parentField);

io.crnk.core.engine.information.resource.ResourceInformation
    public ResourceField findRelationshipFieldByField(ResourceField field) {
     ResourceField resourceField = fieldByJsonName.get(field.getOppositeName());
     if (resourceField == null) {
       resourceField = fieldByUnderlyingName.get(field.getOppositeName());
     }
     return resourceField != null
     && resourceField.getResourceFieldType() == ResourceFieldType.RELATIONSHIP ? resourceField
     : null;
     }

**Comment by remmeier** [comment]
absolutely right, it should directly check the underlyingName-There is no need to compare jsonNames here.

**Comment by franekozulic** [comment]
Thx for the fast reply. 
Is there a possibility to have this fixed in the new release?

**Comment by remmeier** [comment]
found two further spots and changed one of the test cases to make use of @JsonProperty as well. Hope this fixes everything. available this weekend with crnk 3.1.
