### ISSUE TITLE
honor X-Forwarded-Host header for url computation

### ISSUE THREAD

**Issue by datagitlies** [crnk-project/crnk-framework#598]
This issue is similar to #535 in that it deals with `X-Forwarded*` headers being inspected during url construction. The [X-Forwarded-Host](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-Host) header is extremely useful if you're behind a reverse proxy and need HATEOAS links to contain the proper host. Otherwise, you're forced to statically define a `crnk.domain-name` which may not always be feasible / desirable.

**Comment by remmeier** [comment]
I wonder a bit whether it should be the responsiblity of the underlying servlet engine/jaxrs/... to take care of it? what are you using?

**Comment by datagitlies** [comment]
@remmeier I agree, the `X-Forwarded*` headers should be the responsibility of the underlying servlet engine. I'm currently using Tomcat. I think it comes down to the source of the data the code is using to build these URLs. Case in point, I'm not 100% sure if the `HttpServletRequest.getRequestURL()` method will honor these headers behind the scenes or not. I'd need to do more research.

**Comment by remmeier** [comment]
so we don't do anything here? or maybe a FAQ entry?

**Comment by datagitlies** [comment]
@remmeier I'm not 100% sure yet. Spring Boot 2.2.0 was [just released yesterday](https://spring.io/blog/2019/10/16/spring-boot-2-2-0). I'll be pulling it into my project to make sure the updated Tomcat configuration / code works as expected here.  To be continued...

**Comment by datagitlies** [comment]
@remmeier I've confirmed that the updated (auto) configuration of Tomcat via Spring Boot 2.2.0 is working as expected in regards to the `X-Forwarded-Host` header. However, I may need to provide my own `ServiceUrlProvider` since the context root of my proxy is different than the implementation where crnk is running. Do you have any instructions / tips / hints on how I would go about doing that?

**Comment by remmeier** [comment]
CrbkBoot or CrnkBootConfigurer allows to set a new one

Erik Smith <notifications@github.com> schrieb am Mi., 23. Okt. 2019, 14:53:

**Comment by datagitlies** [comment]
@remmeier I was able to get the desired behavior by using Spring Boot 2.2.0 and providing my own `ServiceUrlProvider` implementation via a `CrnkBootConfigurer`  I'll go ahead and close this issue.  Thanks for you help!
