### ISSUE TITLE
Filtering with non-filterable fields

### ISSUE THREAD

**Issue by ryan13mt** [crnk-project/crnk-framework#601]
We are currently using CRNK version 2.11 and have noticed that we are able to filter successfully with fields that should not be filterable.

Fields are annotated with: 
`@JsonApiField(sortable = false, filterable = false, postable = false, patchable = false, readable = false);`

Not sure if problem is solved in CRNK 3 but wanted to see if there is a fix for this.

Thanks

**Comment by remmeier** [comment]
fixed as of now and to be released this weekend as 3.1.

however, there is one limitation: the mechanism is limited to resource attributes and not yet available for nested/embedded attributes. Support for later will come with #399
