### ISSUE TITLE
HttpAdapterListener does not allow to add security headers

### ISSUE THREAD

**Issue by vanwobe** [crnk-project/crnk-framework#602]
from http://www.crnk.io/releases/v3.0/:

> HttpAdapterListener for a vendor-neutral HTTP request/response interception
A new HttpAdapterListener can be added with addListener to HttpAdapter. It allows to cover many of the typical use cases like adding security headers without having to get and customize the underlying HTTP implementation. 

To make this work the io.crnk.spring.client.RestTemplateRequest should postpone the entityReq object creation till after the listeners have been executed (line 62).

regards,
Bert.

**Comment by remmeier** [comment]
fixed and available in 3.1 this weekend
