### ISSUE TITLE
JPA and EmbeddedId: various issues

### ISSUE THREAD

**Issue by jmescheder** [crnk-project/crnk-framework#603]
Hi there, first of all, I am very impressed with the framework so far. Thanks!
I stumbled upon some issues related to JPA Entities using composite primary keys as an EmbeddedId and sorting.

Let's say, we have the following Entity:
_class A {_
_@EmbeddedId_
_B b;_

_String e;_
_}_

This is the embedded ID class:
_class B {_
_// d is defined before c, as we need the generated id in the json to be "d-c"_
_// c is also some kind of sub-category of d, so we want standard sorting to be d, c_
_private Integer d;_
_private Integer c;_
_}_

These are the SQL order by clauses that various request sort parameters produce:

1.	no sort parameter provided
order by **c, d** asc
expected: order by **d, c**
2.	sort=id
order by **c, d** asc
expected: order by **d, c**
3.	sort=-id
order by **c, d desc**
expected: order by **d desc, c desc**
4.	sort=-id.c
order by **c desc, c, d asc**
expected: **order by c desc, d**
 (real problem: considered wrong syntax by most databases)

**Comment by remmeier** [comment]
thank you! can have a look when being back on sunday. the issue linely resides around the CriteriaQueryFactory that tranlates QuerySpec to a JPA query

**Comment by remmeier** [comment]
sorting now down manually for embeddables: honors order of attributes as defined in class, honors direction for all attributes and total order will only sort the missing pieces in ASC order.

official 3.1 release to follow this weekend.
