### ISSUE TITLE
Cannot map different resources to a create request

### ISSUE THREAD

**Issue by kacey-lendi** [crnk-project/crnk-framework#634]
In ResourceRepositoryBase, we have 
public S create(S resource) {
  return save(resource);
}

This means request and response need to be related to 1 resource. We have a request that is completely different to a response. Following crnk approach, do have to put a request resource inside the response resource?

**Comment by remmeier** [comment]
yes, true request and response must be identical in terms of fields (except allowing to leave some thing empty). That is less a crnk issue, more a fundamental property of resource-oriented REST design. If request and response do not match, then there are two possible situation: the use case really does not match the approach or the design can be adapted to follow this approach. But virtually all use cases I came across did fit quite well to the second approach while making the API cleaner.  See http://www.crnk.io/releases/stable/documentation/#_architecture

**Comment by remmeier** [comment]
open up again in case there are more question
