### ISSUE TITLE
Crnk OpenAPI - Duplicate Key (with attribute named id)

### ISSUE THREAD

**Issue by SirBigoo** [crnk-project/crnk-framework#641]
Hello,

I recently added openAPI generation to my project, and I faced a bug on a specific entity I have. I have a JsonAPI / JPA POJO like this : 

```java
public class RuntimeSubproject extends Auditable<String> {
	@JsonProperty
	@Id
	@Column(name = "rps_id", nullable = false)
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private String id;

	@JsonApiId
	@JsonProperty
	@Size(max = 32)
	@Column(name = "rps_subproject_id", nullable = false)
	private String subprojectId;
}
```

When running generation, I have an error : 
```
14:45:40.429 [ERROR] [system.err] Exception in thread "main" java.lang.IllegalStateException: failed to generate class io.crnk.gen.openapi.OpenAPIGeneratorModule, source=io.crnk.gen.runtime.reflections.ReflectionsMetaResolver
14:45:40.429 [ERROR] [system.err]       at io.crnk.gen.gradle.task.ForkedGeneratorMain.main(ForkedGeneratorMain.java:37)
14:45:40.429 [ERROR] [system.err] Caused by: java.lang.IllegalStateException: java.lang.IllegalStateException: Duplicate key SubprojectsIdResourceAttribute (attempted merging values class StringSchema {.......
```

If I rename my field named `id` by something else (like `techId`), it's working.

I suppose this is because my `@JsonApiId` attribute name is not `id` or more logically because my field named `id` is not a `@JsonApiId`. 
I suppose also this is because in openApi generation, field annotated with `@JsonApiId` is renamed `id`, so it has conflict with a field named `id`.

Thanks.

**Comment by remmeier** [comment]
yes true. This is most likely not even related to OpenApi and will lead to issues in various places. The `id` field should either be `@JsonIgnore` or renamemd with `@JsonProperty("someElse")`. It is not something that can be "fixed" I think. But an error should be thrown on startup to do this kind of validation.

**Comment by SirBigoo** [comment]
Well, indeed : it's working by replacing `@JsonProperty` with `@JsonIgnore`. Thanks.

I suppose it's a mistake to put it as a `@JsonProperty` since this `id` field can be ignored : it's just a technical information, no need to retrieve it in any of my resources.

Should I close this issue and create another one as new feature to add this kind of check ?

**Comment by remmeier** [comment]
don,e implemented the check giving the hints discussed here
