### ISSUE TITLE
Can crnk work with Spring MVC?

### ISSUE THREAD

**Issue by jameshwh** [crnk-project/crnk-framework#649]
Hello, My question is similar like the one mentioned here:
https://stackoverflow.com/questions/58243275/use-crnk-without-repository
We know CRNK is repository oriented but we do want to use Spring MVC's controller to expose our rest API, which means requests comes to my controller via url mapping, then use CRNK to wrap the response as a JSON:API output. Not sure if it possible.
Another question is CRNK can generate static swagger documents, can it work with swagger annotations to generate the API document dynamically?

**Comment by remmeier** [comment]
answered https://stackoverflow.com/questions/58243275/use-crnk-without-repository/59293080#59293080

yes, OpenApi as successor to Swagger is supported: http://www.crnk.io/releases/stable/documentation/#_openapi. Quite new and still actively developped, so feedback very welcomed. You find here also one or the other improvement ticket.

**Comment by remmeier** [comment]
you can close the ticket if this answers your question. Or leave it open in case you think the documentation could be improved in an area.
