### ISSUE TITLE
Custom links object broken

### ISSUE THREAD

**Issue by vicmosin** [crnk-project/crnk-framework#657]
Weird error after upgrade to 3.1.20191113192440 for all resources containing custom impls of `JsonApiLinksInformation`..

Here the response:

```
"relationships" : {
      "references" : {
        "data" : null,
        "links" : {
          "self" : "null/relationships/references",
          "related" : "null/references"
        }
      },
      "room" : {
        "data" : {
          "id" : "xxx",
          "type" : "rooms"
        },
        "links" : {
          "self" : "null/relationships/room",
          "related" : "null/room"
        }
      }
```

Any ideas?

**Comment by remmeier** [comment]
`ResourceMapper.getRelationshipLink` computes `the links of relationships based on the self link of the resource. But so far it does not seem to skip this step if the resource itself has no self link. Does this match what you see?

**Comment by remmeier** [comment]
so the resource should have something implementing SelfLinksInformation

**Comment by vicmosin** [comment]
False alarm, tests weren't configured properly (resources's links were not set) and therefor newer version caused them to fail. Thanks :)
