### ISSUE TITLE
OpenAPI crnk-gen-openapi: define openapi servers

### ISSUE THREAD

**Issue by vanwobe** [crnk-project/crnk-framework#661]
The "servers" section defined in the openapi-template seem to be ignored.

The openapi-template contains the following contents:
`{
  "info": {
    "title": "title from template",
    "description": "A generated description of the API from template.",
    "version": "0.0.1-SNAPSHOT"
  },
  "servers": [
    {
      "url": "http://prodserver/event/",
      "description": "Production server (uses live data)"
    },
    {
      "url": "http://devserver/event/",
      "description": "Sandbox server (uses develop data)"
    }
  ]
}`

In the generated yaml file I can see the "info" section was correctly merged but "servers" section was not:

`
openapi: 3.0.1
info:
  title: title from template
  description: A generated description of the API from template.
  version: 0.0.1-SNAPSHOT
servers:
_ url: /
`

**Comment by macleodbroad-wf** [comment]
I was not able to reproduce this issue on current version of master - I added unit tests that demonstrate it working here: https://github.com/crnk-project/crnk-framework/pull/665

If I've misunderstood, please let me know. Thank you.

**Comment by vanwobe** [comment]
Hi,
Indeed with your test json files the generation is working. Comparing the templates I saw that `  "openapi" : "3.0.1",` is the trigger to make this work.
Should it not just work without specifying this?

**Comment by macleodbroad-wf** [comment]
As far as I know, there is no logic in the crnk codebase that would ignore any fields based on the version being specified, however, there is an assumption that the template file you're providing is a valid version 3 openapi file. According to the specification (https://swagger.io/specification/), a string value for the "openapi" field is required in order to be a valid openapi file.

**Comment by vanwobe** [comment]
Well the template is accepted partially because, as I indicated in my initial post, the info part of the template is always being merged.

**Comment by macleodbroad-wf** [comment]
Maybe without specifying the openapi version, it defaults to a version that did not have the servers array, (ie openapi v2/swagger).
