### ISSUE TITLE
JUnit to get a relationship

### ISSUE THREAD

**Issue by rtrinker** [crnk-project/crnk-framework#670]
Hello there

I try to test, if the data of a relationship resource is really the one for my parent resource, if the relation is OneToMany there is no problems with the test, but if I try it with a OneToOne, the test says that my child resource is null, e.g.
**OneToMany:**
`@DisplayName("Find homologation of a vehicle.")
  @Test
  public void findHomologationOfAVehicleTest() {
    Vehicle vehicle = repository.findOne(VEHICLE_ID, new QuerySpec(Vehicle.class));
    Homologation homologation = vehicle.getHomologation().get(0);
    System.out.println(homologation);
    assertEquals(vehicle.getId(), homologation.getVehicleId());
  }`
Result of sysout:
`homologation=io.crnk.client.internal.proxy.CollectionInvocationHandler@68c9d179`

**OneToOne:**
`@DisplayName("Find homologation of a vehicle.")
  @Test
  public void findHomologationOfAVehicleTest() {
    Vehicle vehicle = repository.findOne(VEHICLE_ID, new QuerySpec(Vehicle.class));
    Homologation homologation = vehicle.getHomologation();
    System.out.println(homologation);
    assertEquals(vehicle.getId(), homologation.getVehicleId());
  }`
Result of sysout:
`null`

Or is this not a crnk related problem.

Thank you very much.

**Comment by remmeier** [comment]
all depends on how you do inclusion for your relationships. The given QuerySpec does not specify any. So by default the relationship will not be loaded. So either the QuerySpec will include homologation or you could specify the relationship as being of type EAGER. See http://www.crnk.io/releases/stable/documentation/#_sparse_fieldsets or in the official JSON:API spec  https://jsonapi.org/format/1.1/#fetching-includes.

For collections crnk-client will create a proxy object and fetch it lazy if desired. For single-valued relations it does not do that so far.

**Comment by rtrinker** [comment]
It works with the inclusion now.

Thank you very much.
