### ISSUE TITLE
LinksInformation links as object instead of string

### ISSUE THREAD

**Issue by jbmolle** [crnk-project/crnk-framework#671]
Hi @remmeier 
In JSON:API version 1.1,  links can have href, rel, anchor, params, describedby, meta.
What would you think of changing SelfLinksInformation so it would return a Link instead of a String?

The link interface could be something like this:
public interface Link {

	String getHref();

	void setHref(String href);

	@JsonInclude(JsonInclude.Include.NON_NULL)
	String getAnchor();

	void setAnchor(String anchor);

	@JsonInclude(JsonInclude.Include.NON_NULL)
	LinkParams getParams();

	void setParams(LinkParams params);

	@JsonInclude(JsonInclude.Include.NON_NULL)
	String getDescribedby();

	void setDescribedby(String describedby);

	@JsonInclude(JsonInclude.Include.NON_NULL)
	LinkMeta getMeta();

	void setMeta(LinkMeta meta);
}

So there is the describedby element in link which can point to an OpenApi or JsonSchema reference.

I could work on it if you're interested, let me know.

Best,
JB

**Comment by remmeier** [comment]
would make sense. For relationship, self and paging link, we probably should stick to the short string-based representation. But custom links should be able to do this.

There already is some support for it. See `ClientType.ClientType.OBJECT_LINKS` and `CrnkProperties.SERIALIZE_LINKS_AS_OBJECTS`. But this would fully enforce object-based links more of a hidden feature just now. An explicit link object as you mention would be perfect I think.

**Comment by remmeier** [comment]
we have this now, so closing it. Thank you!
