### ISSUE TITLE
Rollback on exception using JTA-Datasource

### ISSUE THREAD

**Issue by mkassens** [crnk-project/crnk-framework#683]
Hello,
we are trying to use crnk with a jta-datasource (which is managed by the container) but facing the problem that in case of an exception the connection is commited by the container. Probably crnk is catching the exception to send a response with the error to the user, which is fine. But is there any way to have a rollback of the transaction in this case? We have to do multiple updates in case of an save and don't want to commit the first update if the second throws an exception. Or is it not possible to use a container-managed-connection?

Best regards
Michael

**Comment by remmeier** [comment]
Do you make use of `CdiTransactionRunner`?

**Comment by remmeier** [comment]
you can provide your custom implementation, feel free to reopen if there are more questions or something could be contributed.

**Comment by mkassens** [comment]
> you can provide your custom implementation, feel free to reopen if there are more questions or something could be contributed.

Hello again,
yes we are using the CdiTransactionRunner but our problem is that in some cases we are updating/inserting using jooq and not using crnk or the enterprise manager. It seems like in this cases the transaction is not doing a rollback because the transaction is never used because jooq is doing jdbc directly. What would be the best way to do a custom implementation of the CdiTransactionRunner? I think the best way would be just to have a custom CdiTransactionRunnerImpl, but this seems not to be possible because the interface and the impl are in the same lib and it not possible to have to classes implement the CdiTransactionRunner.
