### ISSUE TITLE
Let CrnkExceptionMapper handle errors without details

### ISSUE THREAD

**Issue by remmeier** [crnk-project/crnk-framework#693]
JSON:API spec defines `code`, `title` and `details`. `CrnkExceptionMapper` should use as message for deserialization any of them (in reverse order as listed here).

**Comment by goldyliang** [comment]
Isn't CrnkExceptionMapper already doing this well?  I have been using it to customize them.

**Comment by remmeier** [comment]
issues was here:

```
private String getMessage(ErrorResponse errorResponse) {
        Iterator<ErrorData> errors = errorResponse.getErrors().iterator();
        String message = null;
        if (errors.hasNext()) {
            ErrorData data = errors.next();
            message = data.getDetail();
        }
        return message;
    }

```

this is only during deserialization. Like if any kind of error trigger a 500 status code which in turn translated to a `InternalServerErrorException`. On the server side this might not be a `InternalServerErrorException` and `details` might be left empty. So the commit above changed that. On the server-side nothing changed.
