### ISSUE TITLE
Generating links combined with crnk-client

### ISSUE THREAD

**Issue by ryan13mt** [crnk-project/crnk-framework#696]
Hi @remmeier 

We are using crnk-client in an api-gateway and all is working good. We have a small issue that the links generated by the servlet are pointing to the servlet itself. Therefore when returning the response object to the user, they have the wrong urls since they can only communicate with the gateway. Is there a way we can configure this without hard-coding the gateway url in the servlet? 

Ideally if there is a way to set it in the crnk-client itself it would be perfect.

**Comment by remmeier** [comment]
so `client > gateway > service A` whereas gateway is implemented with crnk-server&client to fowrard anything from `service A`? Note quite sure if I understood all correctly, there are two paths that may fit:

- resources hold links of type `SelfLinksInformation` to maintain the original URL
- there are the various standard `x-forward-...` headers that will influence the URL computation

**Comment by ryan13mt** [comment]
It's user sends one request to gateway, gateway splits call and orchestrates calls with crnk-client to send to main monolith application that has crnk-server, gateway collects all the results and sends only one back to user.

I will try and send the x-forward header with the client since i am only sending the Authorization header.
