### ISSUE TITLE
crnk-core TypeParser throw IllegalArgumentException when parse invalid Enum

### ISSUE THREAD

**Issue by kanonier171** [crnk-project/crnk-framework#710]
Enum's are parsing default by EnumStringMapper, which throw IllegalArgumentException when the specified enum type has no constant with the specified name. This exception is not caught and replace in ParserException which will be better in practice and allow handle exception with information which field is bad

**Comment by remmeier** [comment]
do you have already a fix in mind?

**Comment by kanonier171** [comment]
It's posible to catch IllegalArgumentException in TypedParser, where NumberFormatException is caught and change it to ParserException.

**Comment by remmeier** [comment]
currently there is:

```
public <T> T parse(String input, Class<T> clazz) {
		try {
			if (String.class.equals(clazz)) {
				return (T) input;
			}

			StringParser<T> parser = getParser(clazz, input);
			if (parser == null) {
				throw new ParserException(String.format("Cannot parse to %s : %s", clazz.getName(), input));
			}

			return parser.parse(input);
		}
		catch (NumberFormatException e) {
			throw new ParserException(e.getMessage());
		}
	}
```

mayber it would be better if the parser itself w ould handle the exception. So nNumberFormatException handled in the parser for numbers, an IllegalStateException catched in EnumStringMapper?

**Comment by kanonier171** [comment]
OK

**Comment by remmeier** [comment]
if you have time, PR is very welcomed. Otherwise I should find some time the coming one, two weeks

**Comment by kanonier171** [comment]
#714
