### ISSUE TITLE
Order of attributes are not honored

### ISSUE THREAD

**Issue by goldyliang** [crnk-project/crnk-framework#715]
We have the requirement to order the attributes of JsonAPI responses but there is nothing out-of-the-box to achieve this.

We tried to put the JsonPropertyOrder annotation to the JPA model class, but it does not work. 

I found below code in 
ResourceInformationProviderBase. getResourceFields:

```
        Optional<JsonPropertyOrder> propertyOrder = ClassUtils.getAnnotation(resourceClass, JsonPropertyOrder.class);
        if (propertyOrder.isPresent()) {
            JsonPropertyOrder propertyOrderAnnotation = propertyOrder.get();
            Collections.sort(fields,
                    new FieldOrderedComparator(propertyOrderAnnotation.value(), propertyOrderAnnotation.alphabetic()));
        }
```

So it does try to check the JsonPropertyOrder annotation to sort the order of the fields.

However in ResourceMapper:

```
	protected void setAttributes(Resource resource, Object entity, ResourceInformation resourceInformation,
...
		for (ResourceField field : fields) {
			if (!isIgnored(field, queryContext) && field.getAccess().isReadable()) {
				Object value = field.getAccessor().getValue(entity);
				if (!mappingConfig.isIgnoreDefaults() || !isDefaultValue(value)) {
					setAttribute(resource, field, value);
				}
			}

		}

	protected void setAttribute(Resource resource, ResourceField field, Object value) {
		if (isIncluded(field, value)) {
			JsonNode valueNode = objectMapper.valueToTree(value);
			resource.getAttributes().put(field.getJsonName(), valueNode);
		}
	}

public class Resource extends ResourceIdentifier implements MetaContainer, LinksContainer, ResourceTypeHolder {

....
	@JsonInclude(Include.NON_EMPTY)
	private Map<String, JsonNode> attributes = new HashMap<>();

```

So the thing is, attributes is a HashMap which does not preserve the order of inserted entries.
I think that's why it does not work.

**Comment by remmeier** [comment]
indeed, that was so far not considered important. And yes exactly, `Resource` is the place to look at I think. All the other areas, as far as I know, should already be ok (there are test cases, because in the modelling area the order was already important in the past).

What could be an option is to start making use of LinkedHashMap rather than a basic HashMap?

**Comment by goldyliang** [comment]
Yes I have the same thought that LinkedHashMap shall be used instead.

**Comment by remmeier** [comment]
merged the changed, thank you!
