### ISSUE TITLE
How to disable plain json format?

### ISSUE THREAD

**Issue by snowwolf007cn** [crnk-project/crnk-framework#722]
I found in the document that you can turn it on/off with crnk.config.resource.request.rejectPlainJson
but there is no example on how to setup.

can anyone give me an example?

**Comment by remmeier** [comment]
oh, there seems to be a naming collision. Was not even aware the flag exists anymore. The flag is not related to the relatively new  "simplified json:api" format. But rather inforces the use of application/vn.api++json content type. To disable the plain json format, one can simply drop the dependency in the project. Does this suffice? There is no other configuration flag (so far). But could easily be added.

**Comment by remmeier** [comment]
reopen if you have more questions/input
