### ISSUE TITLE
crnk-gen-openapi: POST/PATCH without "data" top level element 

### ISSUE THREAD

**Issue by peter-plochan** [crnk-project/crnk-framework#724]
I'm little confused about generated OAS files from CRNK. 
For example, when we take [SimpleTasksPostResource](https://github.com/crnk-project/crnk-framework/blob/c4daf5036d2b4b6061056c20b584174e13b47b22/crnk-gen/crnk-gen-openapi/src/test/resources/gold/simple.yaml#L327-L330) from the library test, it says that the input JSON payload should look like this:
```java
{
  "type": "SimpleTasks"
  "attributes": { ... }
}
```
But, this is accepted neither by the CRNK implementation nor by the JSON:API specification itself. It's because there's missing `data` top level element and the payload must look like this:
```java
{
  "data": {
    "type": "SimpleTasks"
    "attributes": { ... }
  }
}
```
So I would like to ask if the generator is intentionally designed like this. If it is, is there a specific reason why? Thanks

**Comment by remmeier** [comment]
I have to look closer since it is an external contribution. But yes, seems that there is the data missing indeed. Have you  by chance also seen the fix in the sources? also any other kind of feedback is welcome to remove the "experimental" sticker on it.

**Comment by peter-plochan** [comment]
Well, the fix should be introduced in [PostResource](https://github.com/crnk-project/crnk-framework/blob/5b684ae1efbe3438b968078dc0f75df2c84156dc/crnk-gen/crnk-gen-openapi/src/main/java/io/crnk/gen/openapi/internal/schemas/PostResource.java#L16) and [PatchResource](https://github.com/crnk-project/crnk-framework/blob/5b684ae1efbe3438b968078dc0f75df2c84156dc/crnk-gen/crnk-gen-openapi/src/main/java/io/crnk/gen/openapi/internal/schemas/PatchResource.java#L16). There's missing `ObjectSchema` with `data` property creation. Something like this:
```java
return new ObjectSchema()
		.required(Collections.singletonList("data"))
		.properties(ImmutableMap.of("data", new ComposedSchema().allOf(...);
```
