### ISSUE TITLE
NEQ filter with multiple values not working

### ISSUE THREAD

**Issue by jnunqui** [crnk-project/crnk-framework#730]
filtering is not applied when using multiples values in NEQ filter: 

&filter[filedName][NEQ]=val1,val2,val3

*when using one single value is working as expected

**Comment by remmeier** [comment]
seems an issue with boolean and/or. comma seperation applies the OR operator for multiple values to check whether either of them matches. But for `NEQ` it should actually be the other way around, it should match none of them.

**Comment by remmeier** [comment]
changes merged, thank you!
