### ISSUE TITLE
Nested resource configuration check unhelpful message

### ISSUE THREAD

**Issue by jimirocks** [crnk-project/crnk-framework#732]
`"resource {} is marked as nested but no parent relationship found"` apparently misses some parameter to be filled in place of `{}`

**Comment by remmeier** [comment]
fixed the `{}` to `%s` in another ticket already and is available on latest/master. The error message is now:

```
        PreconditionUtil.verify(parentField != null, "resource %s is marked as nested but no parent relationship found. Since the " +
				"resource is singular, it carries the same identifier as its parent (stored in the `@JsonApiId` field). To point to the parent, make sure " +
				" the relationship is annotated with @JsonApiRelation(idField=<idField>).", this);
```

Hope this also makes things a bit clearer. Reopen otherwise.

**Comment by remmeier** [comment]
https://github.com/crnk-project/crnk-framework/commit/5b684ae1efbe3438b968078dc0f75df2c84156dc

**Comment by jimirocks** [comment]
Thanks for clarification!
