### ISSUE TITLE
Logout for oauth2 for authorization code grant type.

### ISSUE THREAD

**Issue by MitCoder** [crnk-project/crnk-framework#737]
crnk-framework version: 3.0.20190714142556
spring boot dependencies
```
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-security</artifactId>
    <version>2.2.6.RELEASE</version>
</dependency>
<dependency>
    <groupId>org.springframework.security</groupId>
    <artifactId>spring-security-oauth2-client</artifactId>
    <version>5.2.2.RELEASE</version>
</dependency>
<dependency>
    <groupId>org.springframework.security.oauth.boot</groupId>
    <artifactId>spring-security-oauth2-autoconfigure</artifactId>
    <version>2.2.6.RELEASE</version>
</dependency>
```

I am using oauth2/oidc with authorization code grant type. I have referenced crnk [oauth2 configuration ](https://github.com/crnk-project/crnk-example/blob/master/crnk-example-service/src/main/java/io/crnk/example/service/config/SpringSecurityConfiguration.java)

I am trying to implement a logout feature, which revokes the user's session as well as my spring boot application logs out the user from IdentityProvider.
My security config is as below
```
   @Override
           protected void configure(HttpSecurity http) throws Exception {
                                               
                http
                    .exceptionHandling().authenticationEntryPoint(authenticationEntryPoint())
                    .and()
                    .antMatcher("/v1/**").authorizeRequests()
                    .antMatchers(HttpMethod.GET, "/v1/ user ").authenticated()
                    .antMatchers(HttpMethod.POST, "/v1/logout").authenticated()
                    .and().logout().invalidateHttpSession(false).logoutSuccessUrl("/v1/ user")
                    .and().addFilterBefore(tokenFilter(), BasicAuthenticationFilter.class);
               
                    http.csrf().disable();
            }

            @Bean
            public AuthenticationEntryPoint authenticationEntryPoint() {
                    // May need an OAuth2AuthenticationEntryPoint for non-browser clients
                    return new LoginUrlAuthenticationEntryPoint("/v1/userDirect "); //redirect associated with Auth code grant type. The identity provider consists of redirect url
            }

   private OAuth2ClientAuthenticationProcessingFilter tokenFilter() {
            OAuth2ClientAuthenticationProcessingFilter ibmFilter = new OAuth2ClientAuthenticationProcessingFilter(
                    "/v1/userDirect");//redirect associated with Auth code grant type. The identity provider consists of redirect url 

            ibmFilter.setRestTemplate(oAuth2RestTemplate());
            ibmFilter.setTokenServices(tokenService());

            return ibmFilter;
	   }
```

When I hit my service /v1/user, I am able to integrate with Identity Provider via oidc/authorization code grant type through which the security context gets created with the jwt token associated to the logged in user. But when I try to hit /v1/logout, I either get 404 or 302.

Also if I go as  per,  [crnk oauth2 configuration ](https://github.com/crnk-project/crnk-example/blob/master/crnk-example-service/src/main/java/io/crnk/example/service/config/SpringSecurityConfiguration.java), how do I set the setDefaultTargetUrl. I would like to give back the results associated to "/v1/user" to the caller. Setting only this.setDefaultTargetUrl("/") in setAuthenticationSuccessHandler, I get 404.

@remmeier Maybe you assist me on what is the best way to logout a user/revoke a session within spring boot as well as integrate with identity provider for logging out?

**Comment by remmeier** [comment]
personally I'm not too familiar with Spring security. what do the logs say about `/v1/logout`? I guess that is only served by MVC and crnk is not involved?

**Comment by MitCoder** [comment]
Hello @remmeier, I was able to get the logout working. 
As per your [example](https://github.com/crnk-project/crnk-example/blob/master/crnk-example-service/src/main/java/io/crnk/example/service/config/SpringSecurityConfiguration.java), I think then I removed exceptionHandling().authenticationEntryPoint(authenticationEntryPoint()) and added the below configuration I was able to get logout working for oauth2/oidc. I have used oauth2Login() and oauth2Client() for configuring authorization code grant type with the ID provider for redirect, token handling and userInfo.

```
http.antMatcher("/**").authorizeRequests().antMatchers("/v1/**", "/v1/userDirect", "/userDirect","/v1/logout")
				.authenticated()
				.and()
				// RP-initiated logout
				.logout()
//customLogoutHandler implemented from LogoutHandler to make backed calls to ID provider.
				.addLogoutHandler(revokeLogoutHandler)
				.logoutRequestMatcher(new AntPathRequestMatcher("/v1/logout")) 
				.invalidateHttpSession(true)
                .deleteCookies("JSESSIONID")
                .logoutSuccessHandler(customLogoutSuccessHandler)
				.and()
				.oauth2Login()
					.authorizationEndpoint()
						.authorizationRequestRepository(authorizationRequestRepository())
					.and()
//ClientRegistration bean created with ID provider and client application configuration for auth code grant type
					.clientRegistrationRepository(clientRegistrationRepository())
					.tokenEndpoint()
					.accessTokenResponseClient(accessTokenResponseClient())
					.and()
					.redirectionEndpoint()
					.baseUri("/v1/userInfo")
					.and().userInfoEndpoint()
					.and().and().oauth2Client();


@Bean
public AuthorizationRequestRepository<OAuth2AuthorizationRequest> authorizationRequestRepository() {
		return new HttpSessionOAuth2AuthorizationRequestRepository();
	}
```

**Comment by remmeier** [comment]
ok, thank you! I have a look to maybe enable it in the example to make sure it keeps working.
