### ISSUE TITLE
Openapi spec generation should consider JsonApiResource fields

### ISSUE THREAD

**Issue by gr8web** [crnk-project/crnk-framework#738]
When generating an openapi spec my expection would be that it does not contain endpoint/http method information if it was set to false.

For example if a resource has postable=false defined then the spec should not contain 
post method description.

**Comment by peter-plochan** [comment]
Related to https://github.com/crnk-project/crnk-framework/issues/663 maybe??

**Comment by gr8web** [comment]
Yes, looks like it has been fixed. I will try it with the latest version. Thank you.

**Comment by gr8web** [comment]
Works with the currently latest version.
