### ISSUE TITLE
Ability to add custom Resource Field Type

### ISSUE THREAD

**Issue by samriddhac** [crnk-project/crnk-framework#774]
Is there a way we can add a custom field type within a JsonAPIResource.
Currently, we can have following type of resource field types : -
ID, ATTRIBUTE, RELATIONSHIP, META_INFORMATION, LINKS_INFORMATION.

Is there any way , we can expose additional details like :- 
`{
	"data": [{
		"id": "121",
		"type": "project",
		"links": {
			"self": "http://localhost:12001/project/121"
		},
		"actions": [{
			"name": "action-name"
		}],
		"attributes": {
			"name": "Great Project"
		},
		"relationships": {
			"tasks": {
				"links": {
					"self": "http://localhost:12001/project/121/relationships/tasks",
					"related": "http://localhost:12001/project/121/tasks"
				}
			}
		}
	}]
}`

Please note :- here we want to add this addition field type :- 
`"actions": [{
			"name": "action-name"
		}],`

Yes, we can use meta for the same, but just want to check if we can do the same programmatically.

**Comment by kdsbatra** [comment]
+1

**Comment by remmeier** [comment]
the fields come from JSON:API. "actions" is a topic that comes up quite often. Have you considered modelling those as resources/relationships as well?

**Comment by remmeier** [comment]
modelling it should resolve the issue. Otherwise it possible to intercept the responses of Crnk with DocumentFilter and make any kind of change to the document. But generally I dont recommend doing that.
