### ISSUE TITLE
Bug in `DefaultResourceRepositoryInformationProvider#getPath`?

### ISSUE THREAD

**Issue by dmitrygusev** [crnk-project/crnk-framework#776]
Current implementation is taking `.getResourceType()` from `ResourceInformation`, but should use `.getResourcePath()` I believe:

https://github.com/crnk-project/crnk-framework/blob/ecd7fa9d6f4f191da2fb6bc4ff2460d570c688e0/crnk-core/src/main/java/io/crnk/legacy/repository/information/DefaultResourceRepositoryInformationProvider.java#L99-L101

so it only works when both `resourceType` and `resourcePath` are the same

**Comment by remmeier** [comment]
fixed
