### ISSUE TITLE
Spring boot hibernate Second level Redis cache not working with crnk

### ISSUE THREAD

**Issue by sanjaypatel01** [crnk-project/crnk-framework#782]
On post request data is getting persisted but in get request it is fetching from db not from cache.

I have used below configuration in application.yml file.
    spring.jpa.properties.hibernate.cache:
      use_query_cache: true
      use_second_level_cache: true
      factory_class: org.redisson.hibernate.RedissonRegionFactory
      redisson:
        fallback: true
        config: redisson-dev.yaml

redisson-dev.yaml contains
singleServerConfig:
  address: "redis://localhost:6379"

In class Entity class used below annotation
@org.hibernate.annotations.Cache(region = "producerCache", usage = CacheConcurrencyStrategy.READ_WRITE)

**Comment by remmeier** [comment]
never tried to use it. There is a caching flag on JpaQueryExecutor to enable to Hibernate caching flag. Maybe more is needed in this area.
