### ISSUE TITLE
unable to find opposite field 'questionTemplate' for field ResourceFieldImpl

### ISSUE THREAD

**Issue by mindMaester** [crnk-project/crnk-framework#783]
I want crnk ResourceRepository only for one  User entity, but it tries to create something for QuestionTemplate, is it possible to have only one ResourceRepository without creating it for every entity?

> Caused by: java.lang.IllegalStateException: unable to find opposite field 'questionTemplate' for field ResourceFieldImpl[resourceClass=com.spring.quizz.entity.QuestionTemplate, name=answerTemplates,resourceType=questionTemplate]
> 	at io.crnk.core.engine.internal.utils.PreconditionUtil.fail(PreconditionUtil.java:50) ~[crnk-core-3.3.20200831054147.jar:na]
> 	at io.crnk.core.engine.internal.utils.PreconditionUtil.verify(PreconditionUtil.java:131) ~[crnk-core-3.3.20200831054147.jar:na]
> 	at io.crnk.core.module.ModuleRegistry.initOpposites(ModuleRegistry.java:552) ~[crnk-core-3.3.20200831054147.jar:na]
> 	at io.crnk.core.module.ModuleRegistry.applyResourceRegistrations(ModuleRegistry.java:535) ~[crnk-core-3.3.20200831054147.jar:na]
> 	at io.crnk.core.module.ModuleRegistry.init(ModuleRegistry.java:430) ~[crnk-core-3.3.20200831054147.jar:na]
> 	at io.crnk.core.boot.CrnkBoot.bootDiscovery(CrnkBoot.java:198) ~[crnk-core-3.3.20200831054147.jar:na]
> 	at io.crnk.core.boot.CrnkBoot.boot(CrnkBoot.java:182) ~[crnk-core-3.3.20200831054147.jar:na]
> 	at io.crnk.spring.setup.boot.core.CrnkCoreAutoConfiguration$SpringCrnkBoot.afterPropertiesSet(CrnkCoreAutoConfiguration.java:114) ~[crnk-setup-spring-boot2-3.3.20200831054147.jar:na]
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1804) ~[spring-beans-5.1.2.RELEASE.jar:5.1.2.RELEASE]
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1741) ~[spring-beans-5.1.2.RELEASE.jar:5.1.2.RELEASE]
> 	... 70 common frames omitted

    compile 'io.crnk:crnk-setup-spring-boot2'
    compile 'io.crnk:crnk-format-plain-json'
    compile 'io.crnk:crnk-core'
    compile 'io.crnk:crnk-home'
    compile 'io.crnk:crnk-data-jpa'
    compile 'io.crnk:crnk-validation'
    compile 'io.crnk:crnk-operations'

**Comment by remmeier** [comment]
what is with that field/opposite definition? if itnis defined, it must exist
