### ISSUE TITLE
Generated links are not correct when using load balancer or proxy

### ISSUE THREAD

**Issue by tomivargek** [crnk-project/crnk-framework#785]
Hi, 
we are using Java EE,crnk and Weblogic. We are having problems with generated links (self,relationship, next,prev, etc). When we go through load balancer or proxy, links aren't properly generated. For instance 
[https://portaltest.emilfrey.ch/_wsE122_model-info/ordering/orders?page[limit]=10] (link without load balancer) => generated links are okay 
[https://k5xmf2k2yvwynpcrjbda7pxcx4.apigateway.eu-zurich-1.oci.customer-oci.com/v1/model-info/ordering/orders?page[limit]=10] (link with load balancer/proxy) => generated links aren't proper, they are like this: [https://portaltest.emilfrey.ch/_wsE122_model-info/ordering/orders...).

The problem is links aren't masked (generated) properly. We can't use X-Forward-Headers.. and we were unsuccessful overriding domain-name (crnk resource domain name).

Can you give us any possible solution for this (explain how exactly to override domain name or give us some other proposition of solution)?

Best regards,
TV

**Comment by remmeier** [comment]
CrnkBoot has a ServiceUrlProvider where you can make any kind of customizations. But generally the HOST and X-Forward header would be the way to go. It is in that regard also less crnk related, more general HTTP/HTTP server

**Comment by tomivargek** [comment]
Thanks for your help. We will try to use your advice
