### ISSUE TITLE
Generated selfs links on top level does not respect ServiceUrlProvider

### ISSUE THREAD

**Issue by choeflake** [crnk-project/crnk-framework#789]
The self link which is generated in DocumentMapper (line 146-148) does not take the ServiceUrlProvider in advance. So the resulting link uses the host and path from the request URI. Which could lead to wrong links when the system is behind a proxy / load balancer etc.

**Comment by turtleman** [comment]
Thanks for pekka-ia providing a solution for this issue! Here's hoping the proposed solution fits to the project's goals.

**Comment by choeflake** [comment]
Thanks @pekka-ia looks good! Hopefully the request will be approved soon!

**Comment by pekka-ia** [comment]
I realized there is actually a tricky thing with ServiceUrlProvider and the reactive projects - basically ServiceUrlProvider is attempting to access HttpRequestContext through thread context (HttpRequestContextProvider#33-38) which is not available in reactive settings.

I'll see if I can make this be compatible with both contexts.

**Comment by pekka-ia** [comment]
Looks like on the resource links side this URL building is done like so:

https://github.com/crnk-project/crnk-framework/blob/master/crnk-core/src/main/java/io/crnk/core/engine/internal/registry/ResourceRegistryImpl.java#L117-L120

I'll see if I can introduce similar logic here.

**Comment by pekka-ia** [comment]
I think I have a solid fix now. Instead of attempting to use ServiceUrlProvider, using `requestContext.getBaseUrl()' seems to yield exactly the same results.

When the below config is applied:

`crnk.domain-name: ""`

then

```
GET http://localhost:21120/api/incentive-programs?fields[incentive-programs]=name

{
    "data": [
        {
            "links": {
                "self": "/api/incentive-programs/8377ecb2-d516-4ee1-9fd3-259c54a9119f"
            }
            // rest of the object
        }
    ],
    "links": {
        "self": "/api/incentive-programs?fields[incentive-programs]=name"
    }
}
```

With an explicit domain set, it looks like this:

`crnk.domain-name: "https://www.nbc.com"`

```
GET http://localhost:21120/api/incentive-programs?fields[incentive-programs]=name

{
    "data": [
        {
            "links": {
                "self": "https://www.nbc.com/api/incentive-programs/a2081411-5961-4841-8570-6d538ad51f11"
            }
            // rest of the object
        }
    ],
    "links": {
        "self": "https://www.nbc.com/api/incentive-programs?fields[incentive-programs]=name"
    }
}
```

and with no domain-name configuration set at all, it still works as expected

```
GET http://localhost:21120/api/incentive-programs?fields[incentive-programs]=name
{
    "data": [
        {
            "links": {
                "self": "http://localhost:21120/api/incentive-programs/bf871ce6-8f25-45c9-ae69-71823bbef46b"
            }
            // rest of the object
        }
    ],
    "links": {
        "self": "http://localhost:21120/api/incentive-programs?fields[incentive-programs]=name"
    }
}
```

**Comment by turtleman** [comment]
@pekka-ia, excellent!
