### ISSUE TITLE
Ignore fields in some REST calls

### ISSUE THREAD

**Issue by Apollo-develop** [crnk-project/crnk-framework#805]
Hello,

I would like to ignore fields in some REST calls.

Example:
.../modelA
=> All fields
_________________________________
.../_modelA
=> Only label

OR

../modelA?excludeField=image
=> ignore field image (b64)

OR other solution ?

is it possible ?

Thanks you,

**Comment by remmeier** [comment]
json:api species the field parameter. so kind of. but only as whitelist rather than blacklist. having a fields=-xy to blacklist would be nice to have in the spec.

**Comment by Apollo-develop** [comment]
Thanks so much.

It's good.
