### ISSUE TITLE
Is crnk dead?

### ISSUE THREAD

**Issue by vicmosin** [crnk-project/crnk-framework#806]
Not sure, but seems like no active development going on in 2021..

**Comment by remmeier** [comment]
almost daily questions in the chat. repo open for PRs. at its core it implements the current spec. chat questions seem well covered with that implementation. so there was not too much need in further extending those areas and life is busy in others... quite in contrast to earlier versions running on the katharsis codebase.

there is still a lot of potential for extensions into other areas like serverless and data sources if people feel like it.
