### ISSUE TITLE
Crnk error handling is not compatible with Spring Boot 2.5

### ISSUE THREAD

**Issue by pete-w** [crnk-project/crnk-framework#816]
In particular `CrnkErrorController.errorToJsonApi()` calls `AbstractErrorController.getErrorAttributes()` which takes a `boolean` in 2.4 but in 2.5 expects an `ErrorAttributeOptions` resulting in the following stacktrace:

```
java.lang.NoSuchMethodError: 'java.util.Map io.crnk.spring.setup.boot.mvc.CrnkErrorController.getErrorAttributes(javax.servlet.http.HttpServletRequest, boolean)'
	at io.crnk.spring.setup.boot.mvc.CrnkErrorController.errorToJsonApi(CrnkErrorController.java:39) ~[crnk-setup-spring-boot2-3.4.20210509072026.jar:na]
	at io.crnk.spring.setup.boot.mvc.CrnkErrorController.error(CrnkErrorController.java:64) ~[crnk-setup-spring-boot2-3.4.20210509072026.jar:na]
	...
```

**Comment by datagitlies** [comment]
I too am experiencing this issue.  Below is a link directly to the method that was deprecated in Spring Boot 2.3 and then removed in Spring Boot 2.5 - @remmeier - I'll open a pull request if that will help.

[AbstractErrorController.java:78](https://github.com/spring-projects/spring-boot/blob/2.3.x/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/web/servlet/error/AbstractErrorController.java#L78)

**Comment by datagitlies** [comment]
**Workaround** - In the absence of pull request #821 being accepted and a new version of crnk being released... I'm using the following workaround to just exclude the configuration for the `CrnkErrorController` so I can update Spring Boot to `v2.5.X`

`@SpringBootApplication(exclude = {io.crnk.spring.setup.boot.mvc.CrnkErrorControllerAutoConfiguration.class})`

@pete-w @rohitb1985 @Incanus3
